//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_administrador_valores_cobranza_movs
    {
        public int id_administrador_valores_cobranza_movs { get; set; }
        public Nullable<int> id_admon_valores_g { get; set; }
        public Nullable<int> id_cobranza_movs { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_administrador_valores_g C_administrador_valores_g { get; set; }
    }
}
