//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_APPCLIENT_IMAGENES_PRODUCTOS
    {
        public int id_imagen_producto { get; set; }
        public int id_producto { get; set; }
        public string nombre_imagen { get; set; }
        public int orden { get; set; }
        public bool activo { get; set; }
    }
}
