//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_APPCLIENT_DIRECCIONES
    {
        public int id_cliente_direccion { get; set; }
        public int id_cliente { get; set; }
        public int id_tipo_direccion { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string codigo_sucursal { get; set; }
        public string direccion_completa { get; set; }
        public string num_interior { get; set; }
        public string referencias { get; set; }
        public string colonia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
