//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_APPCLIENT_NOTIFICACIONES
    {
        public int id_notificacion { get; set; }
        public int id_cliente { get; set; }
        public string titulo { get; set; }
        public string cuerpo { get; set; }
        public string imagen { get; set; }
        public int id_tipo_notificacion { get; set; }
        public Nullable<bool> visto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
