//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_APPEMP_TOKENS_PEDIDOS
    {
        public int id_token_pedido { get; set; }
        public string token { get; set; }
        public int id_pedido { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_APPEMP_TOKENS C_APPEMP_TOKENS { get; set; }
        public virtual C_pedidos C_pedidos { get; set; }
    }
}
