//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_autorizaciones_responsables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_autorizaciones_responsables()
        {
            this.C_autorizacion_motivos = new HashSet<C_autorizacion_motivos>();
            this.C_autorizaciones_empleados_cobro = new HashSet<C_autorizaciones_empleados_cobro>();
        }
    
        public int id_responsable { get; set; }
        public string responsable { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> requiere_nip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizacion_motivos> C_autorizacion_motivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_empleados_cobro> C_autorizaciones_empleados_cobro { get; set; }
    }
}
