//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_autorizacion_motivos_tracking
    {
        public int id_motivo_tracking { get; set; }
        public Nullable<int> id_motivo { get; set; }
        public Nullable<int> id_tracking { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
