//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_autorizaciones_comercial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_autorizaciones_comercial()
        {
            this.C_autorizaciones_comercial_d = new HashSet<C_autorizaciones_comercial_d>();
            this.C_sucursales_preparadas = new HashSet<C_sucursales_preparadas>();
        }
    
        public int id_autorizacion_comercial { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_pedido_comercial { get; set; }
        public string nip_autorizador { get; set; }
        public Nullable<bool> en_tiempo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_tipo_movimiento { get; set; }
        public Nullable<int> id_accion_realizada { get; set; }
        public Nullable<int> id_motivo { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_usuario_beneficiado { get; set; }
        public Nullable<int> id_empleado_beneficiado { get; set; }
        public Nullable<bool> revision { get; set; }
        public string observaciones_autorizador { get; set; }
    
        public virtual C_marcas_g C_marcas_g { get; set; }
        public virtual C_pedidos_comercial C_pedidos_comercial { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_comercial_d> C_autorizaciones_comercial_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_preparadas> C_sucursales_preparadas { get; set; }
    }
}
