//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_autorizaciones_comercial_d
    {
        public int id_autorizacion_comercial_d { get; set; }
        public Nullable<int> id_autorizacion_comercial { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_venta_d { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> id_accion_realizada { get; set; }
        public Nullable<int> id_tipo_movimiento { get; set; }
        public Nullable<int> id_motivo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public Nullable<int> id_usuario_autorizador { get; set; }
        public Nullable<int> id_respuesta { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> id_usuario_solicita { get; set; }
    
        public virtual C_autorizacion_acciones C_autorizacion_acciones { get; set; }
        public virtual C_autorizacion_motivos C_autorizacion_motivos { get; set; }
        public virtual C_autorizacion_respuestas C_autorizacion_respuestas { get; set; }
        public virtual C_autorizacion_respuestas C_autorizacion_respuestas1 { get; set; }
        public virtual C_autorizaciones_comercial C_autorizaciones_comercial { get; set; }
        public virtual C_autorizaciones_tipos C_autorizaciones_tipos { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_ventas_d C_ventas_d { get; set; }
    }
}
