//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_autorizacion_solicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_autorizacion_solicitudes()
        {
            this.C_autorizacion_mensajeria = new HashSet<C_autorizacion_mensajeria>();
            this.C_autorizaciones_empleados_cobro = new HashSet<C_autorizaciones_empleados_cobro>();
            this.C_sucursales_preparadas = new HashSet<C_sucursales_preparadas>();
        }
    
        public int id_autorizacion_solicitud { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_tipo_solicitud { get; set; }
        public Nullable<int> id_motivo_solicitud { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_usuario_autorizador { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public Nullable<int> id_respuesta { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_usuario_beneficiado { get; set; }
        public string observaciones2 { get; set; }
        public Nullable<bool> en_tiempo { get; set; }
        public Nullable<bool> vobo { get; set; }
        public string observaciones_vobo { get; set; }
        public Nullable<int> id_usuario_vobo { get; set; }
        public Nullable<int> id_empleado_beneficiado { get; set; }
        public Nullable<bool> cobro { get; set; }
        public Nullable<int> id_empleado_cobro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizacion_mensajeria> C_autorizacion_mensajeria { get; set; }
        public virtual C_autorizacion_motivos C_autorizacion_motivos { get; set; }
        public virtual C_autorizacion_respuestas C_autorizacion_respuestas { get; set; }
        public virtual C_autorizaciones_tipos C_autorizaciones_tipos { get; set; }
        public virtual C_empleados C_empleados { get; set; }
        public virtual C_empleados C_empleados1 { get; set; }
        public virtual C_pedidos C_pedidos { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_empleados_cobro> C_autorizaciones_empleados_cobro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_preparadas> C_sucursales_preparadas { get; set; }
    }
}
