//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_beronna_pedidos
    {
        public int id_pedido_ve { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> interes { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> id_turno { get; set; }
    
        public virtual C_beronna_clientes C_beronna_clientes { get; set; }
        public virtual C_pedidos C_pedidos { get; set; }
    }
}
