//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_historico_detalle
    {
        public int id_detalle { get; set; }
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string folio { get; set; }
        public int folio_id { get; set; }
        public int id_insumo { get; set; }
        public string insumo { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public decimal costo_porcion { get; set; }
        public decimal costo_total { get; set; }
        public string estadoactual { get; set; }
        public string sku_insumo { get; set; }
    }
}
