//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_param_especialidad
    {
        public int id_backorder_param_espec { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_producto_clasificacion { get; set; }
        public Nullable<int> id_especialidad { get; set; }
        public Nullable<decimal> porcentaje_inc_insumo { get; set; }
        public Nullable<decimal> porcentaje_inc_ingredientada { get; set; }
        public Nullable<bool> estatus { get; set; }
    
        public virtual C_producto_clasificacion C_producto_clasificacion { get; set; }
        public virtual C_productos_especialidades C_productos_especialidades { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
