//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bo_backorder_clicks_ajustes
    {
        public int id_bo_click_ajuste { get; set; }
        public Nullable<int> id_backorder { get; set; }
        public string codigo_sucursal { get; set; }
        public string sku_insumo { get; set; }
        public Nullable<decimal> nueva_presentacion_cantidad { get; set; }
        public Nullable<decimal> nuevo_enviar { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_cambio { get; set; }
    
        public virtual C_BO_backorder C_BO_backorder { get; set; }
        public virtual C_insumo_cat C_insumo_cat { get; set; }
    }
}
