//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bonos_sucursales_d
    {
        public int id_bono_sucursal_d { get; set; }
        public string id_bono_sucursal_g { get; set; }
        public string id_empleado { get; set; }
        public string id_rol { get; set; }
        public string monto { get; set; }
        public string fecha { get; set; }
        public string activo { get; set; }
    }
}
