//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_param_clasif_insumos
    {
        public int id_backorder_param_clasif { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_insumo_clasificacion { get; set; }
        public Nullable<decimal> porc_reservado { get; set; }
        public Nullable<decimal> porc_normal { get; set; }
        public Nullable<decimal> porc_mayor { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
