//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_dia_inicio_detalle
    {
        public int id_dia_semana { get; set; }
        public int dia_semana { get; set; }
        public string dia { get; set; }
        public int id_dia_inicio { get; set; }
    }
}
