//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_concentrado_suc
    {
        public int id_backorder_enviar { get; set; }
        public Nullable<int> id_backorder_sucursal { get; set; }
        public string sku_insumo { get; set; }
        public Nullable<decimal> inventario { get; set; }
        public Nullable<decimal> pronostico_fins { get; set; }
        public Nullable<decimal> inventario_transito { get; set; }
        public Nullable<decimal> inventario_pronostico { get; set; }
        public Nullable<decimal> total_calculado { get; set; }
        public Nullable<decimal> enviar { get; set; }
        public Nullable<decimal> presentacion_cantidad { get; set; }
        public Nullable<decimal> total_enviar { get; set; }
        public Nullable<int> id_entrega { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nota_cambio { get; set; }
        public Nullable<decimal> sema_mayor { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
    
        public virtual C_BO_backorder_entregas C_BO_backorder_entregas { get; set; }
        public virtual C_BO_backorder_sucursales C_BO_backorder_sucursales { get; set; }
        public virtual C_insumo_cat C_insumo_cat { get; set; }
        public virtual C_insumo_cat C_insumo_cat1 { get; set; }
    }
}
