//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_log_status
    {
        public int id_log_status { get; set; }
        public Nullable<int> id_entrega { get; set; }
        public Nullable<int> id_status_actual { get; set; }
        public Nullable<int> id_status_nuevo { get; set; }
        public Nullable<System.DateTime> fecha_operacion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
