//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_validador_parametro
    {
        public int id_bo_validador_parametro { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
