//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_porcentaje_prorrateo
    {
        public int id_porcentaje_prorrateo { get; set; }
        public Nullable<int> id_backorder { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_especialidad { get; set; }
        public Nullable<int> id_clasificacion { get; set; }
        public Nullable<double> porcentaje { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
