//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_desvios_detalle
    {
        public int id_desvio_detalle { get; set; }
        public int id_desvio { get; set; }
        public string sku_producto { get; set; }
        public string sku_insumo { get; set; }
        public double cantidad { get; set; }
    }
}
