//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_sucursales_dias
    {
        public int id_sucursal_dia { get; set; }
        public Nullable<int> id_dia { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_subruta { get; set; }
        public Nullable<System.TimeSpan> horario { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> id_ruta { get; set; }
    
        public virtual C_BO_rutas C_BO_rutas { get; set; }
        public virtual C_BO_subrutas C_BO_subrutas { get; set; }
        public virtual C_dias_semana C_dias_semana { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
