//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_reemplazo_g
    {
        public int id_backorder_remplazo_g { get; set; }
        public Nullable<int> id_bo_sucursal_actual { get; set; }
        public Nullable<int> id_bo_sucursal_nuevo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
