//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_log_cambios_entregas
    {
        public int id_log_cambio_entrega { get; set; }
        public Nullable<int> id_backorder { get; set; }
        public Nullable<int> id_entrega { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<System.DateTime> fecha_cambio { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string sku_insumo { get; set; }
        public Nullable<decimal> valor_anterior { get; set; }
        public Nullable<decimal> valor_posterior { get; set; }
        public Nullable<int> id_tipo_alerta { get; set; }
        public string comentarios { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> afecta_entregas { get; set; }
    
        public virtual C_BO_backorder C_BO_backorder { get; set; }
        public virtual C_BO_backorder_entregas C_BO_backorder_entregas { get; set; }
        public virtual C_insumo_cat C_insumo_cat { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_tipo_alertas C_tipo_alertas { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
