//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO_backorder_entregas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_BO_backorder_entregas()
        {
            this.C_BO_backorder_concentrado = new HashSet<C_BO_backorder_concentrado>();
            this.C_BO_backorder_concentrado_suc = new HashSet<C_BO_backorder_concentrado_suc>();
            this.C_BO_backorder_log_cambios_entregas = new HashSet<C_BO_backorder_log_cambios_entregas>();
        }
    
        public int id_entrega { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public Nullable<int> id_backorder { get; set; }
        public Nullable<decimal> porcentaje_entrega { get; set; }
        public Nullable<int> estado_entrega { get; set; }
        public Nullable<int> usuario_genera { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> activo { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_movimiento_insumo { get; set; }
        public Nullable<int> ultimo_movimiento_usuario { get; set; }
        public Nullable<System.DateTime> ultimo_movimiento_fecha { get; set; }
    
        public virtual C_BO_backorder C_BO_backorder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_concentrado> C_BO_backorder_concentrado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_concentrado_suc> C_BO_backorder_concentrado_suc { get; set; }
        public virtual C_BO_backorder_tracking C_BO_backorder_tracking { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_log_cambios_entregas> C_BO_backorder_log_cambios_entregas { get; set; }
    }
}
