//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_cajas_movimientos_cancelados
    {
        public int id_cajas_movimiento_cancelado { get; set; }
        public string id_caja { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_mov { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> id_cajas_tipo_mov { get; set; }
        public Nullable<bool> entrada_salida { get; set; }
        public Nullable<bool> status { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_usuario_recibe { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> id_turno { get; set; }
    
        public virtual C_cajas_tipo_mov C_cajas_tipo_mov { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        public virtual C_usuarios_turnos C_usuarios_turnos { get; set; }
    }
}
