//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_cajas_sucursales_comercial
    {
        public int id_caja_sucursal { get; set; }
        public string id_caja { get; set; }
        public string codigo_sucursal { get; set; }
        public string nom_suc { get; set; }
    }
}
