//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CFDI_Facturas
    {
        public int id_cfdi_fac { get; set; }
        public int id_pedido { get; set; }
        public int id_cliente_cfdi { get; set; }
        public string uuid { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fecha_timbre { get; set; }
        public string nombre_pdf { get; set; }
        public string link_pdf { get; set; }
        public string nombre_xml { get; set; }
        public string path_doc { get; set; }
        public string codigo_sucursal { get; set; }
        public int id_estatus { get; set; }
        public Nullable<int> id_marca { get; set; }
    }
}
