//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CFDI_Clasi_Promos
    {
        public int id_clasi_promos { get; set; }
        public Nullable<int> id_clasificacion { get; set; }
        public Nullable<int> id_promo { get; set; }
        public string unidad_sat { get; set; }
        public string unidad { get; set; }
        public string clave_prod_sat { get; set; }
    }
}
