//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_conciliacion_cobro_d
    {
        public int id_conciliacion_cobro { get; set; }
        public Nullable<int> id_conciliacion_cobro_g { get; set; }
        public string sku_insumo { get; set; }
        public Nullable<decimal> cantidad_solicitada_sistema { get; set; }
        public Nullable<decimal> cantidad_fisica { get; set; }
        public Nullable<decimal> diferencia { get; set; }
        public Nullable<decimal> costo_cobro_unidad { get; set; }
        public Nullable<decimal> costo_cobro_total { get; set; }
        public Nullable<decimal> cantidad_insumo_empleado { get; set; }
        public Nullable<decimal> costo_cobro_empleado { get; set; }
        public Nullable<int> id_usuario_cobro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> estatus_pago { get; set; }
        public Nullable<bool> paso_nomina { get; set; }
        public Nullable<System.DateTime> fecha_paso_nomina { get; set; }
        public string observaciones_nomina { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_conciliacion_cobro_g C_conciliacion_cobro_g { get; set; }
        public virtual C_insumo_cat C_insumo_cat { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
