//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_comisiones_productos
    {
        public int id_comision_producto { get; set; }
        public string codigo_sucursal { get; set; }
        public string sku_producto { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<decimal> precio_publico { get; set; }
        public Nullable<decimal> costo1 { get; set; }
        public Nullable<decimal> costo2 { get; set; }
        public Nullable<int> id_clasificacion { get; set; }
        public Nullable<decimal> calculo_pp_porc { get; set; }
        public Nullable<decimal> calculo_pp_monto { get; set; }
        public Nullable<decimal> calculo_pc1_porc { get; set; }
        public Nullable<decimal> calculo_pc1_monto { get; set; }
        public Nullable<decimal> calculo_pc2_porc { get; set; }
        public Nullable<decimal> calculo_pc2_monto { get; set; }
        public Nullable<decimal> comision_fija_unica { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_producto_clasificacion C_producto_clasificacion { get; set; }
    }
}
