//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_cobranza_tabulador
    {
        public int id_cobranza_tabulador { get; set; }
        public Nullable<int> id_tipo_credito { get; set; }
        public Nullable<decimal> rango_inicio { get; set; }
        public Nullable<decimal> rango_fin { get; set; }
        public Nullable<int> cantidad_pagos { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
