//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_credito_distribuidor_empleados
    {
        public int id_empleado_credito_token { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public string token { get; set; }
        public Nullable<int> id_token { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<int> id_usuario_registra_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<int> id_usuario_registra_pago { get; set; }
        public string observaciones_solicitud { get; set; }
        public string observaciones_pago { get; set; }
        public Nullable<int> estatus_pago { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_caja_mov { get; set; }
    
        public virtual C_credito_estatus_cuenta C_credito_estatus_cuenta { get; set; }
        public virtual C_empleados C_empleados { get; set; }
        public virtual C_pedidos C_pedidos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
    }
}
