//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_credito_movimientos_wallet
    {
        public int id_credito_movimiento { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public string no_gaffette { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<bool> cargo_abono { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public string sku_producto { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_caja_mov { get; set; }
    
        public virtual C_empleados C_empleados { get; set; }
        public virtual C_pedidos C_pedidos { get; set; }
        public virtual C_productos_cat C_productos_cat { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
