//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_App
    {
        public int idApp { get; set; }
        public string app_name { get; set; }
        public string autor { get; set; }
        public Nullable<System.DateTime> last_change { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string description { get; set; }
    }
}
