//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Cliente_Direcciones
    {
        public int id_dir_cliente { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_cliente_zpidi { get; set; }
        public string direccion_entrega { get; set; }
    }
}
