//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Rate
    {
        public int id_rate { get; set; }
        public Nullable<System.DateTime> fecha_rate { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_repartidor { get; set; }
        public Nullable<decimal> rate { get; set; }
    }
}
