//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Plataformas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Delivery_Plataformas()
        {
            this.C_Delivery_Plataformas_Configuracion = new HashSet<C_Delivery_Plataformas_Configuracion>();
            this.C_Delivery_Repartidores_Solicitud = new HashSet<C_Delivery_Repartidores_Solicitud>();
        }
    
        public int id_plataforma { get; set; }
        public string codigo_plataforma { get; set; }
        public string nombre_plataforma { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_Plataformas_Configuracion> C_Delivery_Plataformas_Configuracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_Repartidores_Solicitud> C_Delivery_Repartidores_Solicitud { get; set; }
    }
}
