//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Conversations
    {
        public int id_Conversation { get; set; }
        public Nullable<System.DateTime> dateConversation { get; set; }
        public string tokenSender { get; set; }
        public string tokenClient { get; set; }
        public string messageSender { get; set; }
        public string messageClient { get; set; }
        public Nullable<bool> recibido { get; set; }
        public string phoneNumberClient { get; set; }
        public Nullable<int> idClient { get; set; }
    }
}
