//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Semaforo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Delivery_Semaforo()
        {
            this.C_Delivery_estatus_semaforo_alias = new HashSet<C_Delivery_estatus_semaforo_alias>();
            this.C_Delivery_estatus_semaforo_log = new HashSet<C_Delivery_estatus_semaforo_log>();
            this.C_Delivery_Pre_Orders = new HashSet<C_Delivery_Pre_Orders>();
        }
    
        public int id_semaforo { get; set; }
        public string cve_semaforo { get; set; }
        public string semaforo_descripcion { get; set; }
        public Nullable<int> orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_estatus_semaforo_alias> C_Delivery_estatus_semaforo_alias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_estatus_semaforo_log> C_Delivery_estatus_semaforo_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_Pre_Orders> C_Delivery_Pre_Orders { get; set; }
    }
}
