//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Pagos_Programados
    {
        public int id_orden_pago_g { get; set; }
        public Nullable<System.DateTime> fecha_programada { get; set; }
        public Nullable<int> no_semana { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<decimal> monto_programado { get; set; }
        public string cuenta_origen { get; set; }
        public string cuenta_destino { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tipo_destino { get; set; }
        public Nullable<System.DateTime> fecha_pagada { get; set; }
        public string institucion_bancaria { get; set; }
        public string digitos_cuenta { get; set; }
        public string referencia { get; set; }
        public Nullable<int> estatus_transaccion { get; set; }
        public Nullable<bool> activo { get; set; }
        public string parm_rango_empresas { get; set; }
        public string parm_rango_sucursales { get; set; }
        public string parm_rango_servicios { get; set; }
        public string parm_rango_plataformas { get; set; }
        public string parm_rango_repartidores { get; set; }
        public Nullable<decimal> comisiones { get; set; }
        public Nullable<decimal> a_recuperar { get; set; }
        public Nullable<decimal> monto_aclaracion { get; set; }
    }
}
