//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Negocios_Telefonos_Clientes_Direcciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Delivery_Negocios_Telefonos_Clientes_Direcciones()
        {
            this.C_Delivery_Ordenes_Negocios = new HashSet<C_Delivery_Ordenes_Negocios>();
        }
    
        public int id_telefono_cliente_direccion { get; set; }
        public Nullable<int> id_telefono { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_direccion { get; set; }
    
        public virtual C_Delivery_Negocios_Clientes C_Delivery_Negocios_Clientes { get; set; }
        public virtual C_Delivery_Negocios_Direcciones C_Delivery_Negocios_Direcciones { get; set; }
        public virtual C_Delivery_Negocios_Telefonos C_Delivery_Negocios_Telefonos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_Ordenes_Negocios> C_Delivery_Ordenes_Negocios { get; set; }
    }
}
