//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Repartidores_Ordenes
    {
        public int id { get; set; }
        public int id_order { get; set; }
        public Nullable<int> id_repartidor { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual C_Delivery_Repartidores C_Delivery_Repartidores { get; set; }
    }
}
