//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Repartidores_Vehiculos
    {
        public int id_repartidor_vehiculo { get; set; }
        public Nullable<int> id_repartidor { get; set; }
        public string vehicleId { get; set; }
        public string marca_vehiculo { get; set; }
        public string modelo_vehiculo { get; set; }
        public Nullable<int> anio_vehiculo { get; set; }
        public Nullable<int> color_vehiculo { get; set; }
        public string no_placas { get; set; }
        public string no_permiso { get; set; }
        public Nullable<bool> status_vehiculo { get; set; }
        public string observaciones { get; set; }
    }
}
