//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Setup_Empresas_Suc_Ser_Plat
    {
        public int id_setup_empresas { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> id_plataforma { get; set; }
    }
}
