//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Orders
    {
        public int id_order_g { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> folio { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tea { get; set; }
        public string descripcion_viaje { get; set; }
        public Nullable<int> id_semaforo { get; set; }
        public Nullable<int> id_repartidor { get; set; }
        public string observations { get; set; }
        public string phone { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_domicilios { get; set; }
        public Nullable<int> id_producto { get; set; }
        public string status_viaje { get; set; }
        public Nullable<int> id_new_register { get; set; }
        public Nullable<int> id_reason { get; set; }
        public Nullable<System.TimeSpan> send_time { get; set; }
        public Nullable<System.TimeSpan> time_stopped { get; set; }
        public Nullable<int> id_status { get; set; }
    }
}
