//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Plataformas_Configuracion
    {
        public int id_pataforma_configuracion { get; set; }
        public Nullable<int> id_plataforma { get; set; }
        public Nullable<int> id_tipo_cobro { get; set; }
        public Nullable<int> id_tipo_comision { get; set; }
        public Nullable<int> politica_bloqueo_usuario { get; set; }
        public Nullable<int> politica_dias_pago { get; set; }
        public Nullable<int> dia_pago { get; set; }
        public Nullable<int> politica_manejo_credito { get; set; }
        public Nullable<decimal> limite_credito { get; set; }
        public string no_contrato { get; set; }
        public Nullable<System.DateTime> fecha_inicio_contrato { get; set; }
        public Nullable<System.DateTime> fecha_termino_contrato { get; set; }
        public Nullable<decimal> porcentaje_comision_plat { get; set; }
        public string porcentaje_comision_mens { get; set; }
        public string porcentaje_comision_repa { get; set; }
        public string cuenta_banco_base_10 { get; set; }
        public string cuenta_banco_clabe_18 { get; set; }
        public Nullable<int> id_institucion_bancaria_default { get; set; }
        public Nullable<int> id_moneda_base { get; set; }
        public Nullable<int> politica_zonas { get; set; }
        public string nombre_representante { get; set; }
        public string email_representante { get; set; }
        public Nullable<bool> manejo_membresia_sn { get; set; }
        public Nullable<decimal> monto_acordado_membresia { get; set; }
    
        public virtual C_Delivery_Pais_Moneda C_Delivery_Pais_Moneda { get; set; }
        public virtual C_Delivery_Plataformas C_Delivery_Plataformas { get; set; }
    }
}
