//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Repartidores_Documentacion
    {
        public int doc_id { get; set; }
        public string doc_archivo { get; set; }
        public Nullable<bool> doc_verificado { get; set; }
        public Nullable<int> doc_usu_id { get; set; }
        public Nullable<int> doctip_tipo { get; set; }
    }
}
