//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Trafico_Tracking
    {
        public int id_trafico_tracking { get; set; }
        public Nullable<int> id_orden { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public string est_01 { get; set; }
        public Nullable<System.DateTime> fec_01 { get; set; }
        public string sem_01 { get; set; }
        public Nullable<decimal> dif_01 { get; set; }
        public string est_02 { get; set; }
        public Nullable<System.DateTime> fec_02 { get; set; }
        public string sem_02 { get; set; }
        public Nullable<decimal> dif_02 { get; set; }
        public string est_03 { get; set; }
        public Nullable<System.DateTime> fec_03 { get; set; }
        public string sem_03 { get; set; }
        public Nullable<decimal> dif_03 { get; set; }
        public string est_04 { get; set; }
        public Nullable<System.DateTime> fec_04 { get; set; }
        public string sem_04 { get; set; }
        public Nullable<decimal> dif_04 { get; set; }
        public string est_05 { get; set; }
        public Nullable<System.DateTime> fec_05 { get; set; }
        public string sem_05 { get; set; }
        public Nullable<decimal> dif_05 { get; set; }
        public string est_06 { get; set; }
        public Nullable<System.DateTime> fec_06 { get; set; }
        public string sem_06 { get; set; }
        public Nullable<decimal> dif_06 { get; set; }
        public string est_07 { get; set; }
        public Nullable<System.DateTime> fec_07 { get; set; }
        public string sem_07 { get; set; }
        public Nullable<decimal> dif_07 { get; set; }
        public string est_08 { get; set; }
        public Nullable<System.DateTime> fec_08 { get; set; }
        public string sem_08 { get; set; }
        public Nullable<decimal> dif_08 { get; set; }
        public string est_09 { get; set; }
        public Nullable<System.DateTime> fec_09 { get; set; }
        public string sem_09 { get; set; }
        public Nullable<decimal> dif_09 { get; set; }
        public string est_10 { get; set; }
        public Nullable<System.DateTime> fec_10 { get; set; }
        public string sem_10 { get; set; }
        public Nullable<decimal> dif_10 { get; set; }
        public string est_11 { get; set; }
        public Nullable<System.DateTime> fec_11 { get; set; }
        public string sem_11 { get; set; }
        public Nullable<decimal> dif_11 { get; set; }
        public string est_12 { get; set; }
        public Nullable<System.DateTime> fec_12 { get; set; }
        public string sem_12 { get; set; }
        public Nullable<decimal> dif_12 { get; set; }
        public string est_13 { get; set; }
        public Nullable<System.DateTime> fec_13 { get; set; }
        public string sem_13 { get; set; }
        public Nullable<decimal> dif_13 { get; set; }
        public string est_14 { get; set; }
        public Nullable<System.DateTime> fec_14 { get; set; }
        public string sem_14 { get; set; }
        public Nullable<decimal> dif_14 { get; set; }
        public string est_15 { get; set; }
        public Nullable<System.DateTime> fec_15 { get; set; }
        public string sem_15 { get; set; }
        public Nullable<decimal> dif_15 { get; set; }
        public string est_16 { get; set; }
        public Nullable<System.DateTime> fec_16 { get; set; }
        public string sem_16 { get; set; }
        public Nullable<decimal> dif_16 { get; set; }
        public string est_17 { get; set; }
        public Nullable<System.DateTime> fec_17 { get; set; }
        public string sem_17 { get; set; }
        public Nullable<decimal> dif_17 { get; set; }
        public string est_18 { get; set; }
        public Nullable<System.DateTime> fec_18 { get; set; }
        public string sem_18 { get; set; }
        public Nullable<decimal> dif_18 { get; set; }
        public string est_19 { get; set; }
        public Nullable<System.DateTime> fec_19 { get; set; }
        public string sem_19 { get; set; }
        public Nullable<decimal> dif_19 { get; set; }
        public string est_20 { get; set; }
        public Nullable<System.DateTime> fec_20 { get; set; }
        public string sem_20 { get; set; }
        public Nullable<decimal> dif_20 { get; set; }
        public string est_21 { get; set; }
        public Nullable<System.DateTime> fec_21 { get; set; }
        public string sem_21 { get; set; }
        public Nullable<decimal> dif_21 { get; set; }
        public string est_22 { get; set; }
        public Nullable<System.DateTime> fec_22 { get; set; }
        public string sem_22 { get; set; }
        public Nullable<decimal> dif_22 { get; set; }
        public string est_23 { get; set; }
        public Nullable<System.DateTime> fec_23 { get; set; }
        public string sem_23 { get; set; }
        public Nullable<decimal> dif_23 { get; set; }
        public string est_24 { get; set; }
        public Nullable<System.DateTime> fec_24 { get; set; }
        public string sem_24 { get; set; }
        public Nullable<decimal> dif_24 { get; set; }
        public string est_25 { get; set; }
        public Nullable<System.DateTime> fec_25 { get; set; }
        public string sem_25 { get; set; }
        public Nullable<decimal> dif_25 { get; set; }
        public Nullable<System.DateTime> fec_reasignacion_1 { get; set; }
        public Nullable<System.DateTime> fec_reasignacion_2 { get; set; }
        public Nullable<int> est_reasignacion { get; set; }
        public Nullable<decimal> Calificacion_1 { get; set; }
        public Nullable<decimal> Calificacion_2 { get; set; }
        public Nullable<decimal> Calificacion_3 { get; set; }
        public string nombre_cliente { get; set; }
        public string telefono_cliente { get; set; }
        public Nullable<decimal> saldo_repartidor { get; set; }
        public Nullable<bool> pagada_sn { get; set; }
        public Nullable<System.DateTime> fecha_pagada { get; set; }
        public Nullable<bool> activa { get; set; }
        public Nullable<int> id_repartidor { get; set; }
        public string nombre_repartidor { get; set; }
        public string telefono_repartidor { get; set; }
        public string nombre_sucursal { get; set; }
        public Nullable<int> semaforo_orden { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_plataforma { get; set; }
        public string nombre_plataforma { get; set; }
        public Nullable<decimal> tiempo_total_servicio { get; set; }
        public Nullable<int> est_tiempo_total_servicio { get; set; }
        public string sem_tiempo_total_servicio { get; set; }
    }
}
