//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Parametros
    {
        public int id_parametro { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> valor_numerico { get; set; }
        public string valor_texto { get; set; }
        public Nullable<bool> tipo_parametro { get; set; }
        public string descripcion { get; set; }
    }
}
