//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_estatus_semaforo_log
    {
        public int id_orden_status_log { get; set; }
        public Nullable<int> id_orden { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> status_actual { get; set; }
        public Nullable<int> status_nuevo { get; set; }
        public Nullable<bool> activo { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<bool> ya_llegue { get; set; }
        public string codigo_sucursal { get; set; }
    
        public virtual C_Delivery_Semaforo C_Delivery_Semaforo { get; set; }
    }
}
