//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Mensajes_Whatsapp
    {
        public int id_mensajes_whatsapp { get; set; }
        public string cve_mensaje { get; set; }
        public string header { get; set; }
        public string mensaje { get; set; }
        public string footer { get; set; }
        public string link_a_enviar { get; set; }
        public string id_string { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
