//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_sucursales_gps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Delivery_sucursales_gps()
        {
            this.C_Delivery_Repartidores_Empresas_Sucursales = new HashSet<C_Delivery_Repartidores_Empresas_Sucursales>();
            this.C_Delivery_StartOrders = new HashSet<C_Delivery_StartOrders>();
            this.C_Delivery_Usuarios_Sucursales = new HashSet<C_Delivery_Usuarios_Sucursales>();
        }
    
        public int id_sucursal { get; set; }
        public string codigo_sucursal { get; set; }
        public string nombre_suc { get; set; }
        public int id_empresa { get; set; }
        public double lat { get; set; }
        public double @long { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_Repartidores_Empresas_Sucursales> C_Delivery_Repartidores_Empresas_Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_StartOrders> C_Delivery_StartOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_Usuarios_Sucursales> C_Delivery_Usuarios_Sucursales { get; set; }
    }
}
