//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Notificacion_mensaje
    {
        public int id_notificacion { get; set; }
        public int id_tipo { get; set; }
        public Nullable<int> id_msg_auto { get; set; }
        public string msg { get; set; }
        public System.DateTime fecha { get; set; }
        public bool status { get; set; }
    }
}
