//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Ordenes_Negocios
    {
        public int id_orden_negocio { get; set; }
        public Nullable<int> id_orden { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_telefono_cliente_direccion { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> costo_envio { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_tracking_status { get; set; }
    
        public virtual C_Delivery_Negocios_Telefonos_Clientes_Direcciones C_Delivery_Negocios_Telefonos_Clientes_Direcciones { get; set; }
        public virtual C_Delivery_Negocios_Tracking_Status C_Delivery_Negocios_Tracking_Status { get; set; }
        public virtual C_Delivery_StartOrders C_Delivery_StartOrders { get; set; }
    }
}
