//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Params
    {
        public int id_delivery_parms { get; set; }
        public string params_code { get; set; }
        public string description { get; set; }
        public Nullable<int> param_1_value { get; set; }
        public Nullable<int> param_2_value { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> param_1_amount { get; set; }
        public Nullable<decimal> param_2_amount { get; set; }
    }
}
