//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_StartOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Delivery_StartOrders()
        {
            this.C_Delivery_Repartidores_Ordenes_Reportes = new HashSet<C_Delivery_Repartidores_Ordenes_Reportes>();
            this.C_Delivery_Ordenes_Negocios = new HashSet<C_Delivery_Ordenes_Negocios>();
        }
    
        public int id_order { get; set; }
        public string token { get; set; }
        public string sucursal { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string direccion { get; set; }
        public double lat { get; set; }
        public double @long { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_Repartidores_Ordenes_Reportes> C_Delivery_Repartidores_Ordenes_Reportes { get; set; }
        public virtual C_Delivery_sucursales_gps C_Delivery_sucursales_gps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Delivery_Ordenes_Negocios> C_Delivery_Ordenes_Negocios { get; set; }
    }
}
