//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Repartidores_Pagos_Conceptos
    {
        public int id_repartidores_pagos { get; set; }
        public Nullable<int> id_repartidor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> id_concepto { get; set; }
        public Nullable<int> status { get; set; }
        public string observaciones { get; set; }
    }
}
