//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Ordenes_Bloqueo
    {
        public int id_orden_bloqueo { get; set; }
        public Nullable<int> id_orden { get; set; }
        public string token_repartidor { get; set; }
        public Nullable<bool> disponible { get; set; }
    }
}
