//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Repartidores_p
    {
        public int id_repartidor { get; set; }
        public string nombre { get; set; }
        public string apellido_pat { get; set; }
        public string apellido_mat { get; set; }
        public string sexo { get; set; }
        public System.DateTime fecha_na { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public int telefono { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> cuenta_ban { get; set; }
        public bool activo { get; set; }
    }
}
