//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Colonias
    {
        public int col_id { get; set; }
        public string col_nombre { get; set; }
        public Nullable<int> col_tipo { get; set; }
        public string col_cpostal { get; set; }
        public Nullable<bool> col_activa { get; set; }
        public Nullable<int> zna_id { get; set; }
        public Nullable<int> cda_id { get; set; }
    }
}
