//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Clientes
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string contrasena { get; set; }
        public string telefono { get; set; }
        public string telefono_pwd { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string token { get; set; }
        public Nullable<bool> logeado { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_domicilio { get; set; }
        public string cp { get; set; }
        public Nullable<int> id_usuario_imagen { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<bool> terminos { get; set; }
        public string os { get; set; }
        public Nullable<int> id_google { get; set; }
        public Nullable<int> id_facebook { get; set; }
        public Nullable<int> id_local { get; set; }
        public string score { get; set; }
        public string permisos { get; set; }
        public string appname { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
