//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Pronosticos_Pagos
    {
        public int id_orden_pago { get; set; }
        public Nullable<int> semana { get; set; }
        public Nullable<decimal> monto_pago { get; set; }
        public Nullable<int> id_estatus_orden { get; set; }
        public Nullable<System.DateTime> fecha_programada { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public string referencia { get; set; }
        public Nullable<decimal> importe_total { get; set; }
    }
}
