//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Zonas_Cuadrantes
    {
        public int id_zona { get; set; }
        public string nom_zona { get; set; }
        public Nullable<double> lat1 { get; set; }
        public Nullable<double> long1 { get; set; }
        public Nullable<double> lat2 { get; set; }
        public Nullable<double> long2 { get; set; }
        public Nullable<double> lat3 { get; set; }
        public Nullable<double> long3 { get; set; }
        public Nullable<double> lat4 { get; set; }
        public Nullable<double> long4 { get; set; }
    }
}
