//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Pagos_Programados_Extraordinarios
    {
        public int id_pagos_extraordinarios { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> semana { get; set; }
        public Nullable<System.DateTime> fecha_pago_extra { get; set; }
        public Nullable<int> id_repartidor { get; set; }
        public Nullable<decimal> monto_pago { get; set; }
        public Nullable<int> id_usuario_recibe { get; set; }
        public string nip { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
