//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Pais_Impuestos
    {
        public int id_tipo_impusto { get; set; }
        public Nullable<int> id_pais { get; set; }
        public string nombre_impueto { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> porc_impuesto { get; set; }
        public string alias { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
