//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Delivery_Ordenes_Pagos_Formas
    {
        public int id_pago_tipo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> id_moneda { get; set; }
    }
}
