//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_empleados_cargos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_empleados_cargos()
        {
            this.C_cobranza_corte_d = new HashSet<C_cobranza_corte_d>();
        }
    
        public int id_emplado_cargo { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<decimal> monto_cargo { get; set; }
        public Nullable<int> id_motivo { get; set; }
        public Nullable<System.DateTime> fecha_cargo { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string codigo_sucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_cobranza_corte_d> C_cobranza_corte_d { get; set; }
        public virtual C_empleados C_empleados { get; set; }
        public virtual C_empleados_cargo_motivos C_empleados_cargo_motivos { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
