//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_empleados_tmp
    {
        public int id_empleado { get; set; }
        public string no_empleado { get; set; }
        public string nombres { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public Nullable<int> id_colonia { get; set; }
        public string calle { get; set; }
        public string no_interior { get; set; }
        public string no_exterior { get; set; }
        public Nullable<int> id_ciudad { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public Nullable<int> cp { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string nss { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<int> id_puesto { get; set; }
        public string curp { get; set; }
        public string telefono_celular { get; set; }
        public string telefono_casa { get; set; }
        public string telefono_contacto { get; set; }
        public Nullable<int> id_tipo_sangre { get; set; }
        public string no_gaffete { get; set; }
        public Nullable<int> id_tipo_credito { get; set; }
        public Nullable<int> id_nivel_empleado { get; set; }
        public string tarjeta_empleado { get; set; }
        public Nullable<int> id_estado_visible { get; set; }
        public string codigo_empresa { get; set; }
        public Nullable<bool> id_estado_activo { get; set; }
        public Nullable<int> mc_empleado_id { get; set; }
        public Nullable<int> mc_numero { get; set; }
        public string mc_nombres { get; set; }
        public string mc_ap_paterno { get; set; }
        public string mc_ap_materno { get; set; }
        public Nullable<int> mc_puesto { get; set; }
        public Nullable<int> mc_departamento { get; set; }
        public string mc_fecha_ingreso { get; set; }
        public string mc_curp { get; set; }
        public string mc_fecha_registro { get; set; }
        public string mc_estatus { get; set; }
        public Nullable<System.DateTime> fecha_registro_sinc { get; set; }
        public string app_pwd { get; set; }
        public Nullable<bool> genera_consumos { get; set; }
    }
}
