//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_encuesta_preguntas_subcategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_encuesta_preguntas_subcategoria()
        {
            this.C_encuesta_respuestas = new HashSet<C_encuesta_respuestas>();
        }
    
        public int id_pregunta_subcategoria { get; set; }
        public string pregunta_subcategoria { get; set; }
        public Nullable<int> id_pregunta { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_encuesta_preguntas C_encuesta_preguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_encuesta_respuestas> C_encuesta_respuestas { get; set; }
    }
}
