//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_encuestas_sucursal
    {
        public int id_encuesta_sucursal { get; set; }
        public Nullable<int> id_encuesta { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_encuestas C_encuestas { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
