//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_grupo_difusion
    {
        public int id_grupo_difusion { get; set; }
        public Nullable<int> id_grupo_productos_g { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string nombre_archivo { get; set; }
        public string ubicacion_archivo { get; set; }
        public string url_token { get; set; }
        public Nullable<int> id_usuario_crea { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> identificador { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_grupo_productos_g C_grupo_productos_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
