//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_grupo_productos_codigos_telefonos
    {
        public int id_grupo_productos_codigo_cliente { get; set; }
        public Nullable<int> id_grupo_productos_codigo { get; set; }
        public Nullable<int> id_telefono { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_clientes C_clientes { get; set; }
        public virtual C_grupo_productos_codigos C_grupo_productos_codigos { get; set; }
        public virtual C_telefonos C_telefonos { get; set; }
    }
}
