//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HD_grupos_personas
    {
        public int id_persona { get; set; }
        public Nullable<int> id_grupo_especialistas { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public string correo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_HD_grupos_especialistas C_HD_grupos_especialistas { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
