//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HD_ticket_detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_HD_ticket_detalle()
        {
            this.C_HD_evidencia_reporte = new HashSet<C_HD_evidencia_reporte>();
        }
    
        public int id_ticket_detalle { get; set; }
        public Nullable<int> id_ticket { get; set; }
        public Nullable<int> id_status_tickets { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_HD_evidencia_reporte> C_HD_evidencia_reporte { get; set; }
        public virtual C_HD_status_ticket C_HD_status_ticket { get; set; }
        public virtual C_HD_Ticket C_HD_Ticket { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
