//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HD_subArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_HD_subArea()
        {
            this.C_HD_Categoria = new HashSet<C_HD_Categoria>();
            this.C_HD_grupos_especialistas = new HashSet<C_HD_grupos_especialistas>();
            this.C_HD_Ticket = new HashSet<C_HD_Ticket>();
        }
    
        public int id_subArea { get; set; }
        public string nombre_subArea { get; set; }
        public Nullable<int> id_area { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_HD_area C_HD_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_HD_Categoria> C_HD_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_HD_grupos_especialistas> C_HD_grupos_especialistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_HD_Ticket> C_HD_Ticket { get; set; }
    }
}
