//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_impresion_parametros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_impresion_parametros()
        {
            this.C_impresion_sucursales = new HashSet<C_impresion_sucursales>();
        }
    
        public int id_parametros_printer { get; set; }
        public string nombre_impresora { get; set; }
        public string font_name { get; set; }
        public Nullable<int> font_size_big { get; set; }
        public Nullable<int> font_size_medium { get; set; }
        public Nullable<int> font_size_regular { get; set; }
        public Nullable<int> font_size_small { get; set; }
        public Nullable<int> renglon_inicio { get; set; }
        public Nullable<int> columna_inicio { get; set; }
        public string alias { get; set; }
        public Nullable<bool> estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_impresion_sucursales> C_impresion_sucursales { get; set; }
    }
}
