//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_impresion_log
    {
        public int id_log { get; set; }
        public string codigo_sucursal { get; set; }
        public string parametro1 { get; set; }
        public string parametro2 { get; set; }
        public string parametro3 { get; set; }
        public string parametro4 { get; set; }
        public string parametro5 { get; set; }
        public string nombre_impresora { get; set; }
        public string fecha_impresion { get; set; }
        public int activo { get; set; }
        public string caja { get; set; }
    }
}
