//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_mov_suc_d
    {
        public int id_insumo_mov_d { get; set; }
        public Nullable<int> id_insumo_mov { get; set; }
        public string sku_insumo { get; set; }
        public string sku_producto { get; set; }
        public Nullable<double> cantidad { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> entrada_salida { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_insumo_mov_status { get; set; }
        public Nullable<bool> insumo_subreceta { get; set; }
        public Nullable<decimal> costo_real { get; set; }
        public Nullable<decimal> costo_directo { get; set; }
    
        public virtual C_insumo_cat C_insumo_cat { get; set; }
        public virtual C_insumo_mov_status C_insumo_mov_status { get; set; }
        public virtual C_insumo_mov_suc_g C_insumo_mov_suc_g { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
