//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_clasificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_insumo_clasificacion()
        {
            this.C_BO_backorder_concentrado_porcentajes = new HashSet<C_BO_backorder_concentrado_porcentajes>();
            this.C_BO_backorder_porcentajes_proteccion = new HashSet<C_BO_backorder_porcentajes_proteccion>();
            this.C_BO_rutas_clasificaciones = new HashSet<C_BO_rutas_clasificaciones>();
            this.C_insumo_cat = new HashSet<C_insumo_cat>();
            this.C_insumos_criticos_dias_inventario = new HashSet<C_insumos_criticos_dias_inventario>();
            this.C_insumo_tipo_mov_clasificacion = new HashSet<C_insumo_tipo_mov_clasificacion>();
        }
    
        public int id_insumo_clasif { get; set; }
        public string nombre_insumo { get; set; }
        public string alias_sku { get; set; }
        public Nullable<int> orden_bo_vista { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_concentrado_porcentajes> C_BO_backorder_concentrado_porcentajes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_porcentajes_proteccion> C_BO_backorder_porcentajes_proteccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_rutas_clasificaciones> C_BO_rutas_clasificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_cat> C_insumo_cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumos_criticos_dias_inventario> C_insumos_criticos_dias_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_tipo_mov_clasificacion> C_insumo_tipo_mov_clasificacion { get; set; }
    }
}
