//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_cat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_insumo_cat()
        {
            this.C_bo_backorder_clicks_ajustes = new HashSet<C_bo_backorder_clicks_ajustes>();
            this.C_BO_backorder_concentrado = new HashSet<C_BO_backorder_concentrado>();
            this.C_BO_backorder_concentrado1 = new HashSet<C_BO_backorder_concentrado>();
            this.C_BO_backorder_concentrado_suc = new HashSet<C_BO_backorder_concentrado_suc>();
            this.C_BO_backorder_concentrado_suc1 = new HashSet<C_BO_backorder_concentrado_suc>();
            this.C_BO_backorder_entregas_gral = new HashSet<C_BO_backorder_entregas_gral>();
            this.C_BO_backorder_log_cambios_entregas = new HashSet<C_BO_backorder_log_cambios_entregas>();
            this.C_BO_insumos_embalajes = new HashSet<C_BO_insumos_embalajes>();
            this.C_BO_insumos_embalajes1 = new HashSet<C_BO_insumos_embalajes>();
            this.C_conciliacion_cobro_d = new HashSet<C_conciliacion_cobro_d>();
            this.C_insumo_mov_suc_d = new HashSet<C_insumo_mov_suc_d>();
            this.C_insumo_presentacion = new HashSet<C_insumo_presentacion>();
            this.C_insumo_sucursal = new HashSet<C_insumo_sucursal>();
            this.C_inventario_suc_d = new HashSet<C_inventario_suc_d>();
            this.C_parametro_ingredientadas = new HashSet<C_parametro_ingredientadas>();
            this.C_parametro_ingredientadas1 = new HashSet<C_parametro_ingredientadas>();
            this.C_recetas = new HashSet<C_recetas>();
            this.C_recetas1 = new HashSet<C_recetas>();
            this.C_recetas_log_d = new HashSet<C_recetas_log_d>();
            this.C_subrecetas = new HashSet<C_subrecetas>();
            this.C_subrecetas_d = new HashSet<C_subrecetas_d>();
            this.C_ventas_cierre_inventario = new HashSet<C_ventas_cierre_inventario>();
        }
    
        public int C_id_insumo { get; set; }
        public string sku_insumo { get; set; }
        public string codigo_barra_std { get; set; }
        public string nombre_insumo { get; set; }
        public Nullable<int> id_insumo_clasif { get; set; }
        public Nullable<int> id_insumo_subclasif { get; set; }
        public Nullable<int> id_tipo_inventario { get; set; }
        public Nullable<double> nivel_reorden_insumo { get; set; }
        public Nullable<int> dias_caducidad { get; set; }
        public Nullable<int> C______id_tipo_empaque { get; set; }
        public Nullable<int> C______id_tipo_envase { get; set; }
        public string C______presentacion_cantidad { get; set; }
        public Nullable<int> C______id_unidad { get; set; }
        public Nullable<decimal> C______porc_proteccion { get; set; }
        public Nullable<decimal> C______costo_real { get; set; }
        public Nullable<decimal> C______costo_directo { get; set; }
        public Nullable<bool> inventario_corte { get; set; }
        public Nullable<bool> inventario_general { get; set; }
        public Nullable<bool> bo_incluir { get; set; }
        public string bo_redondeo { get; set; }
        public Nullable<int> bo_provdirecto { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<bool> C______activo { get; set; }
        public string sku_insumo_microsip { get; set; }
        public Nullable<decimal> maximo { get; set; }
        public Nullable<decimal> minimo { get; set; }
        public Nullable<bool> conciliacion { get; set; }
        public Nullable<decimal> costo_conciliacion { get; set; }
        public Nullable<decimal> porc_tolerancia { get; set; }
        public Nullable<bool> aplica_cuadre_conciliacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bo_backorder_clicks_ajustes> C_bo_backorder_clicks_ajustes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_concentrado> C_BO_backorder_concentrado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_concentrado> C_BO_backorder_concentrado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_concentrado_suc> C_BO_backorder_concentrado_suc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_concentrado_suc> C_BO_backorder_concentrado_suc1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_entregas_gral> C_BO_backorder_entregas_gral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_log_cambios_entregas> C_BO_backorder_log_cambios_entregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_insumos_embalajes> C_BO_insumos_embalajes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_insumos_embalajes> C_BO_insumos_embalajes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_conciliacion_cobro_d> C_conciliacion_cobro_d { get; set; }
        public virtual C_insumo_clasificacion C_insumo_clasificacion { get; set; }
        public virtual C_insumo_tipo_empaque C_insumo_tipo_empaque { get; set; }
        public virtual C_insumo_tipo_envase C_insumo_tipo_envase { get; set; }
        public virtual C_unidades_medida C_unidades_medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_mov_suc_d> C_insumo_mov_suc_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_presentacion> C_insumo_presentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_sucursal> C_insumo_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_suc_d> C_inventario_suc_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_parametro_ingredientadas> C_parametro_ingredientadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_parametro_ingredientadas> C_parametro_ingredientadas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_recetas> C_recetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_recetas> C_recetas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_recetas_log_d> C_recetas_log_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_subrecetas> C_subrecetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_subrecetas_d> C_subrecetas_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_cierre_inventario> C_ventas_cierre_inventario { get; set; }
    }
}
