//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Indicadores_Tiempos_Estandar
    {
        public int id_tracking_tmp_estandar { get; set; }
        public int id_tracking { get; set; }
        public int tiempo_minutos { get; set; }
        public string descripcion { get; set; }
    }
}
