//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_mov_masivo_d
    {
        public int id_insumo_mov_masivo_d { get; set; }
        public Nullable<int> id_insumo_mov_masivo { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_insumo_mov_g { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_insumo_mov_masivo C_insumo_mov_masivo { get; set; }
        public virtual C_insumo_mov_suc_g C_insumo_mov_suc_g { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
