//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_cat_log_d
    {
        public int id_insumo_log_d { get; set; }
        public Nullable<int> id_insumo_log_g { get; set; }
        public string sku_insumo { get; set; }
        public string codigo_barra_std { get; set; }
        public string nombre_insumo { get; set; }
        public Nullable<int> id_insumo_clasif { get; set; }
        public Nullable<int> id_tipo_inventario { get; set; }
        public Nullable<double> nivel_reorden_insumo { get; set; }
        public Nullable<int> dias_caducidad { get; set; }
        public Nullable<int> C______id_tipo_empaque { get; set; }
        public Nullable<int> C______id_tipo_envase { get; set; }
        public string C______presentacion_cantidad { get; set; }
        public Nullable<int> C______id_unidad { get; set; }
        public Nullable<decimal> C______porc_proteccion { get; set; }
        public Nullable<decimal> C______costo_real { get; set; }
        public Nullable<decimal> C______costo_directo { get; set; }
        public Nullable<bool> inventario_corte { get; set; }
        public Nullable<bool> inventario_general { get; set; }
        public Nullable<bool> bo_incluir { get; set; }
        public string bo_redondeo { get; set; }
        public Nullable<int> bo_provdirecto { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<bool> C______activo { get; set; }
        public string sku_insumo_microsip { get; set; }
        public Nullable<decimal> maximo { get; set; }
        public Nullable<decimal> minimo { get; set; }
    }
}
