//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_mov_masivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_insumo_mov_masivo()
        {
            this.C_insumo_mov_masivo_d = new HashSet<C_insumo_mov_masivo_d>();
        }
    
        public int id_movimiento_masivo { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_tipo_movimiento { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
    
        public virtual C_insumo_tipo_mov C_insumo_tipo_mov { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_mov_masivo_d> C_insumo_mov_masivo_d { get; set; }
    }
}
