//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_tipo_mov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_insumo_tipo_mov()
        {
            this.C_insumo_mov_masivo = new HashSet<C_insumo_mov_masivo>();
            this.C_insumo_mov_suc_g = new HashSet<C_insumo_mov_suc_g>();
            this.C_insumo_tipo_mov_clasificacion = new HashSet<C_insumo_tipo_mov_clasificacion>();
            this.C_insumo_tipo_mov_rol = new HashSet<C_insumo_tipo_mov_rol>();
        }
    
        public int id_tipo_mov { get; set; }
        public string nombre_movimiento { get; set; }
        public Nullable<bool> entrada_salida { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> aplica_subreceta { get; set; }
        public Nullable<bool> e_s_subreceta { get; set; }
        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_mov_masivo> C_insumo_mov_masivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_mov_suc_g> C_insumo_mov_suc_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_tipo_mov_clasificacion> C_insumo_tipo_mov_clasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_tipo_mov_rol> C_insumo_tipo_mov_rol { get; set; }
    }
}
