//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumos_criticos_dias_inventario
    {
        public int Id_cdi { get; set; }
        public Nullable<int> dia { get; set; }
        public Nullable<int> tipo_inventario { get; set; }
        public Nullable<int> Id_clasificacion { get; set; }
    
        public virtual C_insumo_clasificacion C_insumo_clasificacion { get; set; }
        public virtual C_insumos_criticos_tipos C_insumos_criticos_tipos { get; set; }
    }
}
