//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_ingredientada
    {
        public int id_inventario_ingredientada { get; set; }
        public Nullable<int> id_inventario { get; set; }
        public string sku_producto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_inventario_suc_g C_inventario_suc_g { get; set; }
        public virtual C_productos_cat C_productos_cat { get; set; }
    }
}
