//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_log_pedidos_repartidor
    {
        public int id_log_pedido_repartidor { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<decimal> tiempo_esperado { get; set; }
        public Nullable<decimal> tiempo_realizado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> num_orden { get; set; }
        public Nullable<int> num_ruta { get; set; }
        public Nullable<bool> prestar_cambio { get; set; }
        public Nullable<bool> stand_by { get; set; }
    
        public virtual C_pedidos C_pedidos { get; set; }
    }
}
