//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_log_autorizaciones_nip
    {
        public int id_log_autorizaciones_nip { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_usuario_nip { get; set; }
        public string nip { get; set; }
        public Nullable<System.DateTime> fecha_utilizacion { get; set; }
        public string accion { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
