//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_mesas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_mesas()
        {
            this.C_pedidos = new HashSet<C_pedidos>();
            this.C_pedidos_comercial = new HashSet<C_pedidos_comercial>();
            this.C_usuarios_mesas = new HashSet<C_usuarios_mesas>();
        }
    
        public int id_mesa { get; set; }
        public Nullable<int> id_tipo_mesa { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<int> numero_mesa { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_zona { get; set; }
        public Nullable<int> id_subzona { get; set; }
        public string margin_right { get; set; }
        public string margin_left { get; set; }
        public string margin_top { get; set; }
        public string margin_bottom { get; set; }
        public Nullable<int> id_usuario_mesero { get; set; }
    
        public virtual C_mesa_tipo C_mesa_tipo { get; set; }
        public virtual C_mesas_status C_mesas_status { get; set; }
        public virtual C_subzonas C_subzonas { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_zonas C_zonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_pedidos> C_pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_pedidos_comercial> C_pedidos_comercial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_mesas> C_usuarios_mesas { get; set; }
    }
}
