//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_mensajeria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_mensajeria()
        {
            this.C_mensajeria_destinatarios = new HashSet<C_mensajeria_destinatarios>();
        }
    
        public int id_mensaje { get; set; }
        public string asunto { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_termino { get; set; }
        public string url_multimedia { get; set; }
        public Nullable<int> id_tipo_multimedia { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tipo_mensaje { get; set; }
        public Nullable<int> id_clasificacion_mensaje { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_mensajeria_destinatarios> C_mensajeria_destinatarios { get; set; }
    }
}
