//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_microsip_dptos_sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_microsip_dptos_sucursales()
        {
            this.C_cobranza_corte_d = new HashSet<C_cobranza_corte_d>();
        }
    
        public int id_microsip_deps_sucs { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public string nombre_departamento { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_entidad { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_cobranza_corte_d> C_cobranza_corte_d { get; set; }
    }
}
