//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_microsip_bajas_log
    {
        public int id_microsip_baja_log { get; set; }
        public Nullable<int> mc_empleado_id { get; set; }
        public Nullable<int> mc_numero { get; set; }
        public Nullable<System.DateTime> fecha_cambio { get; set; }
    }
}
