//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_microsip_empleados_no_registrados
    {
        public int id_microsip_no_alta { get; set; }
        public int id_microsip { get; set; }
        public int numero { get; set; }
        public string nombres { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public int puesto { get; set; }
        public int departamento { get; set; }
        public string fecha_ingreso { get; set; }
        public string fecha_registro { get; set; }
        public string estatus { get; set; }
    }
}
