//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_microsip_empleados_cambio_depa_cajeros
    {
        public int id_mc_empleado_cajero { get; set; }
        public int id_usuario_corporativo { get; set; }
        public string codigo_sucursal_antigua { get; set; }
        public string codigo_sucursal_nueva { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int id_cambio_estatus { get; set; }
    }
}
