//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_parametros_configuracion
    {
        public int id_parametro_configuracion { get; set; }
        public string parametro { get; set; }
        public Nullable<decimal> valor_numerico { get; set; }
        public string valor_texto { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
