//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_pedidos_ticket_status
    {
        public int id_pedidos_ticket_status { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<bool> status_ticket { get; set; }
    
        public virtual C_pedidos C_pedidos { get; set; }
    }
}
