//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_pedidos_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_pedidos_d()
        {
            this.C_autorizaciones_empleados_cobro = new HashSet<C_autorizaciones_empleados_cobro>();
            this.C_warmer_preparadas = new HashSet<C_warmer_preparadas>();
        }
    
        public int id_pedido_d { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public string sku_producto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<bool> pedido_d_status { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<bool> preparar_cocina { get; set; }
        public Nullable<bool> descontar_inventario { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<bool> warmer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_empleados_cobro> C_autorizaciones_empleados_cobro { get; set; }
        public virtual C_pedidos C_pedidos { get; set; }
        public virtual C_productos_cat C_productos_cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_warmer_preparadas> C_warmer_preparadas { get; set; }
    }
}
