//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_pedidos_descuentos
    {
        public int id_pedido_descuento { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_descuento { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> cantidad_descuento { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> id_usuario_autoriza { get; set; }
        public Nullable<System.DateTime> fecha_descuento { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
