//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_plan_comercial_facturacion_d
    {
        public int id_plan_comercial_facturacion_d { get; set; }
        public Nullable<int> id_plan_comercial_facturacion { get; set; }
        public Nullable<int> id_plan_comercial { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_plan_comercial_facturacion C_plan_comercial_facturacion { get; set; }
    }
}
