//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_plan_comercial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_plan_comercial()
        {
            this.C_plan_comercial_d = new HashSet<C_plan_comercial_d>();
        }
    
        public int id_plan_comercial { get; set; }
        public string codigo_sucursal { get; set; }
        public System.DateTime fecha_meta { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<int> ordenes { get; set; }
        public Nullable<decimal> cantidad_real { get; set; }
        public Nullable<bool> estatus { get; set; }
        public string sku_producto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_plan_comercial_d> C_plan_comercial_d { get; set; }
    }
}
