//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_productos_cat_log_d
    {
        public int id_producto_log_d { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_clasificacion { get; set; }
        public Nullable<int> id_subclasificacion { get; set; }
        public Nullable<int> id_especialidad { get; set; }
        public Nullable<decimal> precio_publico { get; set; }
        public Nullable<decimal> costo_directo { get; set; }
        public Nullable<decimal> costo_real { get; set; }
        public Nullable<int> id_producto_log_g { get; set; }
    
        public virtual C_producto_subclasificacion C_producto_subclasificacion { get; set; }
        public virtual C_productos_cat_log_g C_productos_cat_log_g { get; set; }
        public virtual C_productos_especialidades C_productos_especialidades { get; set; }
    }
}
