//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_producto_base_tipo
    {
        public int id_preducto_base_tipo { get; set; }
        public Nullable<int> id_categoria_base { get; set; }
        public Nullable<int> id_producto_tipo { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
