//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_productos_cat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_productos_cat()
        {
            this.C_autorizaciones_empleados_cobro = new HashSet<C_autorizaciones_empleados_cobro>();
            this.C_credito_movimientos_wallet = new HashSet<C_credito_movimientos_wallet>();
            this.C_impuesto_producto = new HashSet<C_impuesto_producto>();
            this.C_inventario_ingredientada = new HashSet<C_inventario_ingredientada>();
            this.C_inventario_suc_d = new HashSet<C_inventario_suc_d>();
            this.C_pedidos_d = new HashSet<C_pedidos_d>();
            this.C_produccion_generada_d = new HashSet<C_produccion_generada_d>();
            this.C_producto_presentacion = new HashSet<C_producto_presentacion>();
            this.C_productos_cat_log_g = new HashSet<C_productos_cat_log_g>();
            this.C_productos_marca = new HashSet<C_productos_marca>();
            this.C_productos_plataforma_d = new HashSet<C_productos_plataforma_d>();
            this.C_productos_sucursal = new HashSet<C_productos_sucursal>();
            this.C_recetas = new HashSet<C_recetas>();
            this.C_recetas_log_d = new HashSet<C_recetas_log_d>();
            this.C_sucursales_preparadas = new HashSet<C_sucursales_preparadas>();
            this.C_ventas_d = new HashSet<C_ventas_d>();
            this.C_warmer_d = new HashSet<C_warmer_d>();
            this.C_warmer_preparadas = new HashSet<C_warmer_preparadas>();
            this.C_warmer_productos = new HashSet<C_warmer_productos>();
        }
    
        public int id_producto { get; set; }
        public string sku { get; set; }
        public string plu { get; set; }
        public string codigo_barra { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_producto_clasificacion { get; set; }
        public Nullable<int> id_producto_subclasificacion { get; set; }
        public Nullable<int> id_especialidad { get; set; }
        public Nullable<int> id_catalogo_tamanos { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public Nullable<decimal> maximo { get; set; }
        public Nullable<decimal> minimo { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_ultima_compra { get; set; }
        public Nullable<bool> incluir_backorder { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public Nullable<int> id_producto_presentacion { get; set; }
        public Nullable<bool> insumos { get; set; }
        public Nullable<bool> activo { get; set; }
        public string path_imagen { get; set; }
        public Nullable<int> id_clase { get; set; }
        public Nullable<bool> devolucion_inventario { get; set; }
        public Nullable<bool> preparacion { get; set; }
        public Nullable<decimal> token_ganancia { get; set; }
        public Nullable<bool> aplica_token { get; set; }
        public Nullable<bool> comision_venta { get; set; }
        public Nullable<decimal> monto_comision_venta { get; set; }
        public Nullable<bool> conciliacion { get; set; }
        public Nullable<bool> aplica_ingredientada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_empleados_cobro> C_autorizaciones_empleados_cobro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_credito_movimientos_wallet> C_credito_movimientos_wallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_impuesto_producto> C_impuesto_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_ingredientada> C_inventario_ingredientada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_suc_d> C_inventario_suc_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_pedidos_d> C_pedidos_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_produccion_generada_d> C_produccion_generada_d { get; set; }
        public virtual C_producto_clasificacion C_producto_clasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_producto_presentacion> C_producto_presentacion { get; set; }
        public virtual C_producto_subclasificacion C_producto_subclasificacion { get; set; }
        public virtual C_productos_clase C_productos_clase { get; set; }
        public virtual C_productos_especialidades C_productos_especialidades { get; set; }
        public virtual C_unidades_medida C_unidades_medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_productos_cat_log_g> C_productos_cat_log_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_productos_marca> C_productos_marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_productos_plataforma_d> C_productos_plataforma_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_productos_sucursal> C_productos_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_recetas> C_recetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_recetas_log_d> C_recetas_log_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_preparadas> C_sucursales_preparadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_d> C_ventas_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_warmer_d> C_warmer_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_warmer_preparadas> C_warmer_preparadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_warmer_productos> C_warmer_productos { get; set; }
    }
}
