//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_produccion_generada_d
    {
        public int id_produccion_generada_d { get; set; }
        public Nullable<int> id_produccion_generada { get; set; }
        public Nullable<int> cantidad_solicitada { get; set; }
        public Nullable<int> cantidad_realizada { get; set; }
        public string sku_producto { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_produccion_generada C_produccion_generada { get; set; }
        public virtual C_productos_cat C_productos_cat { get; set; }
    }
}
