//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_rappi_tipo_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_rappi_tipo_status()
        {
            this.C_rappi_log_tracking = new HashSet<C_rappi_log_tracking>();
            this.C_rappi_log_tracking1 = new HashSet<C_rappi_log_tracking>();
            this.C_rappi_ordenes_g = new HashSet<C_rappi_ordenes_g>();
        }
    
        public int id_tipo_estatus_rappi { get; set; }
        public string tipo_estatus { get; set; }
        public string color { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_rappi_log_tracking> C_rappi_log_tracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_rappi_log_tracking> C_rappi_log_tracking1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_rappi_ordenes_g> C_rappi_ordenes_g { get; set; }
    }
}
