//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_rappi_productos
    {
        public int id_rappi_productos { get; set; }
        public string codigo_sucursal { get; set; }
        public string sku_producto { get; set; }
        public string nombre_producto_rappi { get; set; }
        public string descripcion_producto { get; set; }
        public Nullable<decimal> precio_rappi { get; set; }
        public string nombre_promo_rappi { get; set; }
        public string nombre_categoria { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
