//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_rappi_log_tracking
    {
        public int id_log_tracking_estatus { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_estatus_actual { get; set; }
        public Nullable<int> id_nuevo_estatus { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> usuario_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_rappi_tipo_status C_rappi_tipo_status { get; set; }
        public virtual C_rappi_tipo_status C_rappi_tipo_status1 { get; set; }
    }
}
