//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_rappi_ordenes_pedidos
    {
        public int C_rappi_ordenes_pedidos1 { get; set; }
        public Nullable<int> id_pedido_rappi { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
    
        public virtual C_pedidos C_pedidos { get; set; }
        public virtual C_rappi_ordenes_g C_rappi_ordenes_g { get; set; }
    }
}
