//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_recetas_log_d
    {
        public int id_receta_log_d { get; set; }
        public string sku_producto { get; set; }
        public string sku_insumo { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> costo_total { get; set; }
        public Nullable<decimal> costo_porcion { get; set; }
        public Nullable<int> id_log_modificacion { get; set; }
    
        public virtual C_insumo_cat C_insumo_cat { get; set; }
        public virtual C_log_modificaciones_g C_log_modificaciones_g { get; set; }
        public virtual C_productos_cat C_productos_cat { get; set; }
    }
}
