//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_solicitudes_repartidor
    {
        public int id_solicitud_repartidor { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_atiende { get; set; }
        public Nullable<int> id_usuario_atiende { get; set; }
        public Nullable<System.DateTime> fecha_asigna_repartidor { get; set; }
        public Nullable<int> id_usuario_asigna_repartidor { get; set; }
        public Nullable<int> id_status_solicitud { get; set; }
        public Nullable<int> id_empleado_repartidor { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_solicitudes_repartidor_status C_solicitudes_repartidor_status { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo2 { get; set; }
    }
}
