//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_sucursales()
        {
            this.C_administrador_valores_g = new HashSet<C_administrador_valores_g>();
            this.C_agenda_d = new HashSet<C_agenda_d>();
            this.C_autorizacion_solicitudes = new HashSet<C_autorizacion_solicitudes>();
            this.C_autorizacion_usuarios = new HashSet<C_autorizacion_usuarios>();
            this.C_autorizaciones_comercial_d = new HashSet<C_autorizaciones_comercial_d>();
            this.C_autorizaciones_empleados_cobro = new HashSet<C_autorizaciones_empleados_cobro>();
            this.C_BO_backorder_entregas = new HashSet<C_BO_backorder_entregas>();
            this.C_BO_backorder_log_cambios_entregas = new HashSet<C_BO_backorder_log_cambios_entregas>();
            this.C_BO_backorder_param_clasif = new HashSet<C_BO_backorder_param_clasif>();
            this.C_BO_backorder_param_entrega = new HashSet<C_BO_backorder_param_entrega>();
            this.C_BO_backorder_param_especialidad = new HashSet<C_BO_backorder_param_especialidad>();
            this.C_BO_backorder_porcentajes_proteccion = new HashSet<C_BO_backorder_porcentajes_proteccion>();
            this.C_BO_backorder_sucursales = new HashSet<C_BO_backorder_sucursales>();
            this.C_BO_backorder_sucursales_dias = new HashSet<C_BO_backorder_sucursales_dias>();
            this.C_BO_dias_festivos = new HashSet<C_BO_dias_festivos>();
            this.C_BO_rutas_sucursales = new HashSet<C_BO_rutas_sucursales>();
            this.C_cajas_movimientos_cancelados = new HashSet<C_cajas_movimientos_cancelados>();
            this.C_cajas_retiro_dias = new HashSet<C_cajas_retiro_dias>();
            this.C_cajas_sucursales = new HashSet<C_cajas_sucursales>();
            this.C_cobranza_corte_d = new HashSet<C_cobranza_corte_d>();
            this.C_direcciones_sucursales = new HashSet<C_direcciones_sucursales>();
            this.C_empleados_cargos = new HashSet<C_empleados_cargos>();
            this.C_empresas_sucursales = new HashSet<C_empresas_sucursales>();
            this.C_encuestas_sucursal = new HashSet<C_encuestas_sucursal>();
            this.C_equipo_sucursal = new HashSet<C_equipo_sucursal>();
            this.C_grupo_productos_codigos_movs = new HashSet<C_grupo_productos_codigos_movs>();
            this.C_HD_Ticket = new HashSet<C_HD_Ticket>();
            this.C_impresion_sucursales = new HashSet<C_impresion_sucursales>();
            this.C_insumo_mov_masivo_d = new HashSet<C_insumo_mov_masivo_d>();
            this.C_insumo_mov_suc_d = new HashSet<C_insumo_mov_suc_d>();
            this.C_insumo_sucursal = new HashSet<C_insumo_sucursal>();
            this.C_inventario_suc_g = new HashSet<C_inventario_suc_g>();
            this.C_log_servicio_delivery = new HashSet<C_log_servicio_delivery>();
            this.C_log_servicio_delivery1 = new HashSet<C_log_servicio_delivery>();
            this.C_login_empleados = new HashSet<C_login_empleados>();
            this.C_parametros_sucursales = new HashSet<C_parametros_sucursales>();
            this.C_pedidos = new HashSet<C_pedidos>();
            this.C_produccion_generada = new HashSet<C_produccion_generada>();
            this.C_productos_plataforma_d = new HashSet<C_productos_plataforma_d>();
            this.C_productos_sucursal = new HashSet<C_productos_sucursal>();
            this.C_servicios_sucursal = new HashSet<C_servicios_sucursal>();
            this.C_solicitudes_repartidor = new HashSet<C_solicitudes_repartidor>();
            this.C_sucursales1 = new HashSet<C_sucursales>();
            this.C_sucursales_colonias = new HashSet<C_sucursales_colonias>();
            this.C_sucursales_config = new HashSet<C_sucursales_config>();
            this.C_sucursales_marcas = new HashSet<C_sucursales_marcas>();
            this.C_sucursales_preparadas = new HashSet<C_sucursales_preparadas>();
            this.C_sucursales_warmer = new HashSet<C_sucursales_warmer>();
            this.C_usuarios_sucursales = new HashSet<C_usuarios_sucursales>();
            this.C_ventas_g = new HashSet<C_ventas_g>();
            this.C_ventas_g1 = new HashSet<C_ventas_g>();
            this.C_vex_plan_meta_b3 = new HashSet<C_vex_plan_meta_b3>();
            this.C_warmer_g = new HashSet<C_warmer_g>();
            this.C_warmer_preparadas = new HashSet<C_warmer_preparadas>();
            this.C_warmer_productos = new HashSet<C_warmer_productos>();
            this.C_warmer_sucursales = new HashSet<C_warmer_sucursales>();
            this.C_zonas_sucursales = new HashSet<C_zonas_sucursales>();
            this.C_usuarios_sucursales_extra = new HashSet<C_usuarios_sucursales_extra>();
        }
    
        public int Id_sucursal { get; set; }
        public string codigo_sucursal { get; set; }
        public string nombre { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public bool servicio_mostrador { get; set; }
        public Nullable<int> id_motivo_servicio_mostrador { get; set; }
        public Nullable<bool> servicio_reparto { get; set; }
        public Nullable<int> id_motivo_servicio_reparto { get; set; }
        public Nullable<bool> desvio { get; set; }
        public Nullable<int> id_direccion { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_zona_precio { get; set; }
        public string ip { get; set; }
        public Nullable<bool> activo { get; set; }
        public string sucursal_desvio { get; set; }
        public Nullable<bool> requiere_repartidor { get; set; }
        public Nullable<System.TimeSpan> hora_apertura { get; set; }
        public Nullable<System.TimeSpan> hora_cierre { get; set; }
        public Nullable<int> id_tipo_venta { get; set; }
        public Nullable<bool> servicio_rappi { get; set; }
        public Nullable<bool> autorizacion_solicitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_administrador_valores_g> C_administrador_valores_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_agenda_d> C_agenda_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizacion_solicitudes> C_autorizacion_solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizacion_usuarios> C_autorizacion_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_comercial_d> C_autorizaciones_comercial_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_empleados_cobro> C_autorizaciones_empleados_cobro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_entregas> C_BO_backorder_entregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_log_cambios_entregas> C_BO_backorder_log_cambios_entregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_param_clasif> C_BO_backorder_param_clasif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_param_entrega> C_BO_backorder_param_entrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_param_especialidad> C_BO_backorder_param_especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_porcentajes_proteccion> C_BO_backorder_porcentajes_proteccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_sucursales> C_BO_backorder_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_backorder_sucursales_dias> C_BO_backorder_sucursales_dias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_dias_festivos> C_BO_dias_festivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BO_rutas_sucursales> C_BO_rutas_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_cajas_movimientos_cancelados> C_cajas_movimientos_cancelados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_cajas_retiro_dias> C_cajas_retiro_dias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_cajas_sucursales> C_cajas_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_cobranza_corte_d> C_cobranza_corte_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_direcciones_sucursales> C_direcciones_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_empleados_cargos> C_empleados_cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_empresas_sucursales> C_empresas_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_encuestas_sucursal> C_encuestas_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_equipo_sucursal> C_equipo_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_grupo_productos_codigos_movs> C_grupo_productos_codigos_movs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_HD_Ticket> C_HD_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_impresion_sucursales> C_impresion_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_mov_masivo_d> C_insumo_mov_masivo_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_mov_suc_d> C_insumo_mov_suc_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_sucursal> C_insumo_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_suc_g> C_inventario_suc_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_log_servicio_delivery> C_log_servicio_delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_log_servicio_delivery> C_log_servicio_delivery1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_login_empleados> C_login_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_parametros_sucursales> C_parametros_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_pedidos> C_pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_produccion_generada> C_produccion_generada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_productos_plataforma_d> C_productos_plataforma_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_productos_sucursal> C_productos_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_servicios_sucursal> C_servicios_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_solicitudes_repartidor> C_solicitudes_repartidor { get; set; }
        public virtual C_sucursal_status_motivo C_sucursal_status_motivo { get; set; }
        public virtual C_sucursal_status_motivo C_sucursal_status_motivo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales> C_sucursales1 { get; set; }
        public virtual C_sucursales C_sucursales2 { get; set; }
        public virtual C_sucursales_direcciones C_sucursales_direcciones { get; set; }
        public virtual C_zonas_precio C_zonas_precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_colonias> C_sucursales_colonias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_config> C_sucursales_config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_marcas> C_sucursales_marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_preparadas> C_sucursales_preparadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_warmer> C_sucursales_warmer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_sucursales> C_usuarios_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_g> C_ventas_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_g> C_ventas_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_vex_plan_meta_b3> C_vex_plan_meta_b3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_warmer_g> C_warmer_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_warmer_preparadas> C_warmer_preparadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_warmer_productos> C_warmer_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_warmer_sucursales> C_warmer_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_zonas_sucursales> C_zonas_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_sucursales_extra> C_usuarios_sucursales_extra { get; set; }
    }
}
