//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sucursales_pool_division_impresion
    {
        public int id_suc_pool_tipos { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> tipo_division_impresion { get; set; }
        public string descripcion { get; set; }
        public string nombre_impresora { get; set; }
    }
}
