//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sucursales_pool_clasificaciones
    {
        public int id_suc_pool_imp_clasifica { get; set; }
        public string alias_tipo { get; set; }
        public string id_producto_clasificacion { get; set; }
        public string descripcion_tipo { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
