//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sucursales_preparadas
    {
        public int id_sucursales_preparadas { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string sku_producto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_razon { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> id_accion_realizar { get; set; }
        public Nullable<int> id_solicitud_autorizacion { get; set; }
        public Nullable<int> id_accion_realizada { get; set; }
        public Nullable<bool> disponible_venta { get; set; }
        public Nullable<int> id_usuario_autoriza { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public Nullable<int> id_pedido_acomodo { get; set; }
        public Nullable<System.DateTime> fecha_acomodo { get; set; }
        public Nullable<int> usuario_cobro { get; set; }
        public Nullable<int> id_pedido_comercial { get; set; }
        public Nullable<int> id_autorizacion_comercial { get; set; }
        public Nullable<int> id_venta_d { get; set; }
        public Nullable<int> id_pedido_d { get; set; }
    
        public virtual C_autorizacion_acciones C_autorizacion_acciones { get; set; }
        public virtual C_autorizacion_solicitudes C_autorizacion_solicitudes { get; set; }
        public virtual C_autorizaciones_comercial C_autorizaciones_comercial { get; set; }
        public virtual C_pedidos_comercial C_pedidos_comercial { get; set; }
        public virtual C_productos_cat C_productos_cat { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_sucursales_razones C_sucursales_razones { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_ventas_d C_ventas_d { get; set; }
    }
}
