//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sucursales_credito
    {
        public int id_sucursal_credito { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public string sku_producto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
