//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sucursales_ip
    {
        public int id_sucursal_ip { get; set; }
        public string codigo_sucursal { get; set; }
        public string ip_add { get; set; }
        public string path_ruta { get; set; }
        public string alias { get; set; }
        public string ip_sucursal { get; set; }
        public string caja { get; set; }
        public string path_impresion_local { get; set; }
        public string path_impresion_servidor { get; set; }
        public Nullable<int> switch_nor_xml { get; set; }
        public Nullable<int> ex1 { get; set; }
        public Nullable<int> ex2 { get; set; }
        public Nullable<int> ex3 { get; set; }
        public Nullable<int> ex4 { get; set; }
        public Nullable<int> ex5 { get; set; }
        public string id_usuario_sesion { get; set; }
        public Nullable<System.DateTime> fecha_ultima_sesion { get; set; }
    }
}
