//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_telefonos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_telefonos()
        {
            this.C_clientes_telefono = new HashSet<C_clientes_telefono>();
            this.C_grupo_productos_codigos_telefonos = new HashSet<C_grupo_productos_codigos_telefonos>();
            this.C_pedidos = new HashSet<C_pedidos>();
            this.C_pedidos_comercial = new HashSet<C_pedidos_comercial>();
        }
    
        public int id_telefono { get; set; }
        public string telefono { get; set; }
        public Nullable<int> id_pregunta_web { get; set; }
        public string respuesta { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_clientes_telefono> C_clientes_telefono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_grupo_productos_codigos_telefonos> C_grupo_productos_codigos_telefonos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_pedidos> C_pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_pedidos_comercial> C_pedidos_comercial { get; set; }
        public virtual C_preguntas_web C_preguntas_web { get; set; }
    }
}
