//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tipo_alerta_rol
    {
        public int id_alerta_rol { get; set; }
        public Nullable<int> id_tipo_alerta { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_tipo_alertas C_tipo_alertas { get; set; }
        public virtual C_usuarios_roles C_usuarios_roles { get; set; }
    }
}
