//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_usuarios_perfil_incentivos_roles
    {
        public int id_usuarios_perfil_roles { get; set; }
        public Nullable<int> id_usuarios_perfil_rangos { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<decimal> monto_comision { get; set; }
    }
}
