//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_usuarios_roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_usuarios_roles()
        {
            this.C_autorizaciones_tipo_permiso_roles = new HashSet<C_autorizaciones_tipo_permiso_roles>();
            this.C_encuesta_rol = new HashSet<C_encuesta_rol>();
            this.C_HD_modulos_sub_permisos = new HashSet<C_HD_modulos_sub_permisos>();
            this.C_HD_usuario_tipo_roles = new HashSet<C_HD_usuario_tipo_roles>();
            this.C_mensajeria_destinatarios = new HashSet<C_mensajeria_destinatarios>();
            this.C_modulos_sub_permisos = new HashSet<C_modulos_sub_permisos>();
            this.C_servicios_roles = new HashSet<C_servicios_roles>();
            this.C_tipo_alerta_rol = new HashSet<C_tipo_alerta_rol>();
            this.C_usuarios_corporativo = new HashSet<C_usuarios_corporativo>();
            this.C_usuarios_corporativo1 = new HashSet<C_usuarios_corporativo>();
            this.C_usuarios_roles_montos = new HashSet<C_usuarios_roles_montos>();
            this.C_usuarios_roles_multi = new HashSet<C_usuarios_roles_multi>();
        }
    
        public int id_rol { get; set; }
        public string nombre_rol { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> puesto_id { get; set; }
        public string puesto_nombre { get; set; }
        public Nullable<decimal> sueldo_diario { get; set; }
        public Nullable<decimal> sueldo_diario_max { get; set; }
        public Nullable<int> sucursales_corporativo { get; set; }
        public Nullable<int> id_ms_departamento { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> externos { get; set; }
        public string avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_tipo_permiso_roles> C_autorizaciones_tipo_permiso_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_encuesta_rol> C_encuesta_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_HD_modulos_sub_permisos> C_HD_modulos_sub_permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_HD_usuario_tipo_roles> C_HD_usuario_tipo_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_mensajeria_destinatarios> C_mensajeria_destinatarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_modulos_sub_permisos> C_modulos_sub_permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_servicios_roles> C_servicios_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tipo_alerta_rol> C_tipo_alerta_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_corporativo> C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_corporativo> C_usuarios_corporativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_roles_montos> C_usuarios_roles_montos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_roles_multi> C_usuarios_roles_multi { get; set; }
    }
}
