//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ventas_cierre_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_ventas_cierre_g()
        {
            this.C_ventas_cierre_d = new HashSet<C_ventas_cierre_d>();
            this.C_ventas_cierre_inventario = new HashSet<C_ventas_cierre_inventario>();
        }
    
        public int id_venta_cierre { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<int> id_usuario_cierre { get; set; }
        public Nullable<decimal> monto_venta { get; set; }
        public string notas { get; set; }
        public Nullable<decimal> monto_requerido { get; set; }
        public Nullable<decimal> diferencia { get; set; }
        public string id_caja { get; set; }
        public Nullable<int> id_cierre_tipo { get; set; }
        public Nullable<int> numero_cierre { get; set; }
        public Nullable<int> id_turno { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_turnos C_usuarios_turnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_cierre_d> C_ventas_cierre_d { get; set; }
        public virtual C_ventas_cierre_tipo C_ventas_cierre_tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_cierre_inventario> C_ventas_cierre_inventario { get; set; }
    }
}
