//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ventas_cierre_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_ventas_cierre_d()
        {
            this.C_ventas_cierre_d_cobros = new HashSet<C_ventas_cierre_d_cobros>();
            this.C_ventas_cierre_d_cobros_nip = new HashSet<C_ventas_cierre_d_cobros_nip>();
            this.C_ventas_cierre_d1 = new HashSet<C_ventas_cierre_d1>();
            this.C_ventas_cierre_d2 = new HashSet<C_ventas_cierre_d2>();
            this.C_ventas_cierre_d3 = new HashSet<C_ventas_cierre_d3>();
        }
    
        public int id_ventas_cierre_det { get; set; }
        public Nullable<int> id_venta_cierre_g { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<decimal> efectivo_sistema { get; set; }
        public Nullable<decimal> efectivo_captura { get; set; }
        public Nullable<decimal> efectivo_diferencia { get; set; }
        public Nullable<decimal> tarjeta_sistema { get; set; }
        public Nullable<decimal> tarjeta_captura { get; set; }
        public Nullable<decimal> tarjeta_diferencia { get; set; }
        public Nullable<decimal> total_diferencia { get; set; }
        public Nullable<decimal> fondo_captura { get; set; }
        public Nullable<decimal> fondo_sistema { get; set; }
        public Nullable<decimal> fondo_diferencia { get; set; }
        public string observaciones { get; set; }
    
        public virtual C_ventas_cierre_g C_ventas_cierre_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_cierre_d_cobros> C_ventas_cierre_d_cobros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_cierre_d_cobros_nip> C_ventas_cierre_d_cobros_nip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_cierre_d1> C_ventas_cierre_d1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_cierre_d2> C_ventas_cierre_d2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_cierre_d3> C_ventas_cierre_d3 { get; set; }
    }
}
