//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ventas_cierre_transito
    {
        public int id_venta_cierre_transito { get; set; }
        public Nullable<int> id_venta_g { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public string repartidor { get; set; }
        public string fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
