//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ventas_pedido_comercial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_ventas_pedido_comercial()
        {
            this.C_ventas_pagos_comercial = new HashSet<C_ventas_pagos_comercial>();
            this.C_ventas_pedido_comercial_d = new HashSet<C_ventas_pedido_comercial_d>();
        }
    
        public int id_venta_pedido_comercial { get; set; }
        public Nullable<int> id_pedido_comercial { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> propina { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<int> id_venta_status { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_cierra { get; set; }
        public string id_caja_cierra { get; set; }
        public Nullable<decimal> pago_recibido { get; set; }
    
        public virtual C_pedidos_comercial C_pedidos_comercial { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_pagos_comercial> C_ventas_pagos_comercial { get; set; }
        public virtual C_ventas_status C_ventas_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_pedido_comercial_d> C_ventas_pedido_comercial_d { get; set; }
    }
}
