//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_vex_plan_meta_segmento_semana
    {
        public int id_vex { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> semana { get; set; }
        public Nullable<int> no_pedidos { get; set; }
        public string tipo { get; set; }
        public Nullable<decimal> venta { get; set; }
    }
}
