//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_vex_plan_meta_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_vex_plan_meta_g()
        {
            this.C_vex_plan_meta_b1 = new HashSet<C_vex_plan_meta_b1>();
            this.C_vex_plan_meta_b2 = new HashSet<C_vex_plan_meta_b2>();
            this.C_vex_plan_meta_b3 = new HashSet<C_vex_plan_meta_b3>();
            this.C_vex_plan_meta_params = new HashSet<C_vex_plan_meta_params>();
        }
    
        public int id_vex_plan_meta_g { get; set; }
        public Nullable<System.DateTime> fecha_calculo { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_mes_calculo { get; set; }
        public Nullable<int> id_anio_calculo { get; set; }
        public Nullable<System.DateTime> fecha_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_vex_plan_meta_b1> C_vex_plan_meta_b1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_vex_plan_meta_b2> C_vex_plan_meta_b2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_vex_plan_meta_b3> C_vex_plan_meta_b3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_vex_plan_meta_params> C_vex_plan_meta_params { get; set; }
    }
}
