//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ventas_cierre_comercial_g
    {
        public int id_venta_cierre_comercial { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<int> id_usuario_cierre { get; set; }
        public Nullable<decimal> monto_venta { get; set; }
        public string id_caja { get; set; }
        public string notas { get; set; }
        public Nullable<int> id_tipo_cierre { get; set; }
    
        public virtual C_marcas_g C_marcas_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
