//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ventas_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_ventas_d()
        {
            this.C_autorizaciones_comercial_d = new HashSet<C_autorizaciones_comercial_d>();
            this.C_sucursales_preparadas = new HashSet<C_sucursales_preparadas>();
            this.C_ventas_pedido_comercial_d = new HashSet<C_ventas_pedido_comercial_d>();
        }
    
        public int id_venta_d { get; set; }
        public string sku_producto { get; set; }
        public Nullable<int> id_venta_g { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> id_promocion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<bool> pagado { get; set; }
        public string notas { get; set; }
        public Nullable<int> id_tipo_autorizacion { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public Nullable<int> id_grupo_productos_prods { get; set; }
        public Nullable<bool> preparacion { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> id_promocion_grupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_autorizaciones_comercial_d> C_autorizaciones_comercial_d { get; set; }
        public virtual C_autorizaciones_tipos C_autorizaciones_tipos { get; set; }
        public virtual C_grupo_productos_prods C_grupo_productos_prods { get; set; }
        public virtual C_productos_cat C_productos_cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sucursales_preparadas> C_sucursales_preparadas { get; set; }
        public virtual C_ventas_g C_ventas_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ventas_pedido_comercial_d> C_ventas_pedido_comercial_d { get; set; }
    }
}
