//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_warmer_preparadas
    {
        public int id_warmer_preparadas { get; set; }
        public string codigo_sucursal { get; set; }
        public string sku_producto { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<int> id_pedido_d { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_usuario_venta { get; set; }
        public Nullable<int> id_turno { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_warmer_g { get; set; }
        public Nullable<int> id_status_warmer { get; set; }
        public Nullable<int> hora { get; set; }
    
        public virtual C_pedidos C_pedidos { get; set; }
        public virtual C_pedidos_d C_pedidos_d { get; set; }
        public virtual C_productos_cat C_productos_cat { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_turnos C_usuarios_turnos { get; set; }
        public virtual C_warmer_g C_warmer_g { get; set; }
        public virtual C_warmer_status C_warmer_status { get; set; }
    }
}
