//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_web_log
    {
        public int id_web_log { get; set; }
        public Nullable<int> numero_clic { get; set; }
        public string nombre_clic { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string telefono { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
