//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_zonas_sucursales
    {
        public int id_zona_sucursal { get; set; }
        public Nullable<int> id_zona { get; set; }
        public string codigo_sucursal { get; set; }
    
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_zonas C_zonas { get; set; }
    }
}
