//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_zonas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_zonas()
        {
            this.C_mesas = new HashSet<C_mesas>();
            this.C_subzonas = new HashSet<C_subzonas>();
            this.C_usuarios_zonas = new HashSet<C_usuarios_zonas>();
            this.C_zonas_marcas = new HashSet<C_zonas_marcas>();
            this.C_zonas_sucursales = new HashSet<C_zonas_sucursales>();
        }
    
        public int id_zona { get; set; }
        public string zona { get; set; }
        public string alias { get; set; }
        public Nullable<int> id_planta { get; set; }
        public Nullable<int> id_ubicacion { get; set; }
        public Nullable<decimal> largo { get; set; }
        public Nullable<decimal> ancho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_mesas> C_mesas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_subzonas> C_subzonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_zonas> C_usuarios_zonas { get; set; }
        public virtual C_zonas_plantas C_zonas_plantas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_zonas_marcas> C_zonas_marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_zonas_sucursales> C_zonas_sucursales { get; set; }
    }
}
