//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_a872a9_gomotorsEntities : DbContext
    {
        public db_a872a9_gomotorsEntities()
            : base("name=db_a872a9_gomotorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_administrador_valores> C_administrador_valores { get; set; }
        public virtual DbSet<C_administrador_valores_cobranza_movs> C_administrador_valores_cobranza_movs { get; set; }
        public virtual DbSet<C_administrador_valores_d> C_administrador_valores_d { get; set; }
        public virtual DbSet<C_administrador_valores_g> C_administrador_valores_g { get; set; }
        public virtual DbSet<C_administrador_valores_status> C_administrador_valores_status { get; set; }
        public virtual DbSet<C_agenda> C_agenda { get; set; }
        public virtual DbSet<C_agenda_d> C_agenda_d { get; set; }
        public virtual DbSet<C_agenda_status> C_agenda_status { get; set; }
        public virtual DbSet<C_agenda_tipo_actividad> C_agenda_tipo_actividad { get; set; }
        public virtual DbSet<C_almacen_insumos> C_almacen_insumos { get; set; }
        public virtual DbSet<C_almacen_tipo> C_almacen_tipo { get; set; }
        public virtual DbSet<C_almacenes> C_almacenes { get; set; }
        public virtual DbSet<C_APPCLIENT_BANNERS> C_APPCLIENT_BANNERS { get; set; }
        public virtual DbSet<C_APPCLIENT_CATEGORIAS_MENU> C_APPCLIENT_CATEGORIAS_MENU { get; set; }
        public virtual DbSet<C_APPCLIENT_CLASIFICACIONES> C_APPCLIENT_CLASIFICACIONES { get; set; }
        public virtual DbSet<C_APPCLIENT_CLIENTES> C_APPCLIENT_CLIENTES { get; set; }
        public virtual DbSet<C_APPCLIENT_DIRECCIONES> C_APPCLIENT_DIRECCIONES { get; set; }
        public virtual DbSet<C_APPCLIENT_IMAGENES_PRODUCTOS> C_APPCLIENT_IMAGENES_PRODUCTOS { get; set; }
        public virtual DbSet<C_APPCLIENT_NOTIFICACIONES> C_APPCLIENT_NOTIFICACIONES { get; set; }
        public virtual DbSet<C_APPCLIENT_PEDIDOS> C_APPCLIENT_PEDIDOS { get; set; }
        public virtual DbSet<C_APPCLIENT_PRODUCTOS> C_APPCLIENT_PRODUCTOS { get; set; }
        public virtual DbSet<C_APPCLIENT_PRODUCTOS_FAV> C_APPCLIENT_PRODUCTOS_FAV { get; set; }
        public virtual DbSet<C_APPEMP_TOKENS> C_APPEMP_TOKENS { get; set; }
        public virtual DbSet<C_APPEMP_TOKENS_ESTATUS> C_APPEMP_TOKENS_ESTATUS { get; set; }
        public virtual DbSet<C_APPEMP_TOKENS_PEDIDOS> C_APPEMP_TOKENS_PEDIDOS { get; set; }
        public virtual DbSet<C_autorizacion_acciones> C_autorizacion_acciones { get; set; }
        public virtual DbSet<C_autorizacion_mensajeria> C_autorizacion_mensajeria { get; set; }
        public virtual DbSet<C_autorizacion_motivos> C_autorizacion_motivos { get; set; }
        public virtual DbSet<C_autorizacion_motivos_tracking> C_autorizacion_motivos_tracking { get; set; }
        public virtual DbSet<C_autorizacion_respuestas> C_autorizacion_respuestas { get; set; }
        public virtual DbSet<C_autorizacion_solicitudes> C_autorizacion_solicitudes { get; set; }
        public virtual DbSet<C_autorizacion_tipo_permisos_nip> C_autorizacion_tipo_permisos_nip { get; set; }
        public virtual DbSet<C_autorizacion_usuarios> C_autorizacion_usuarios { get; set; }
        public virtual DbSet<C_autorizaciones_comercial> C_autorizaciones_comercial { get; set; }
        public virtual DbSet<C_autorizaciones_comercial_d> C_autorizaciones_comercial_d { get; set; }
        public virtual DbSet<C_autorizaciones_empleados_cobro> C_autorizaciones_empleados_cobro { get; set; }
        public virtual DbSet<C_autorizaciones_responsables> C_autorizaciones_responsables { get; set; }
        public virtual DbSet<C_autorizaciones_tipo_permiso_roles> C_autorizaciones_tipo_permiso_roles { get; set; }
        public virtual DbSet<C_autorizaciones_tipos> C_autorizaciones_tipos { get; set; }
        public virtual DbSet<C_autorizadores_nip> C_autorizadores_nip { get; set; }
        public virtual DbSet<C_beronna_clientes> C_beronna_clientes { get; set; }
        public virtual DbSet<C_beronna_pedidos> C_beronna_pedidos { get; set; }
        public virtual DbSet<C_bo_almacen> C_bo_almacen { get; set; }
        public virtual DbSet<C_BO_backorder> C_BO_backorder { get; set; }
        public virtual DbSet<C_bo_backorder_clicks_ajustes> C_bo_backorder_clicks_ajustes { get; set; }
        public virtual DbSet<C_BO_backorder_concentrado> C_BO_backorder_concentrado { get; set; }
        public virtual DbSet<C_BO_backorder_concentrado_porcentajes> C_BO_backorder_concentrado_porcentajes { get; set; }
        public virtual DbSet<C_BO_backorder_concentrado_suc> C_BO_backorder_concentrado_suc { get; set; }
        public virtual DbSet<C_BO_backorder_criterios> C_BO_backorder_criterios { get; set; }
        public virtual DbSet<C_BO_backorder_entregas> C_BO_backorder_entregas { get; set; }
        public virtual DbSet<C_BO_backorder_entregas_gral> C_BO_backorder_entregas_gral { get; set; }
        public virtual DbSet<C_BO_backorder_insumos> C_BO_backorder_insumos { get; set; }
        public virtual DbSet<C_BO_backorder_log_cambios_entregas> C_BO_backorder_log_cambios_entregas { get; set; }
        public virtual DbSet<C_BO_backorder_log_status> C_BO_backorder_log_status { get; set; }
        public virtual DbSet<C_BO_backorder_param_clasif> C_BO_backorder_param_clasif { get; set; }
        public virtual DbSet<C_BO_backorder_param_clasif_insumos> C_BO_backorder_param_clasif_insumos { get; set; }
        public virtual DbSet<C_BO_backorder_param_entrega> C_BO_backorder_param_entrega { get; set; }
        public virtual DbSet<C_BO_backorder_param_especialidad> C_BO_backorder_param_especialidad { get; set; }
        public virtual DbSet<C_BO_backorder_porcentaje_prorrateo> C_BO_backorder_porcentaje_prorrateo { get; set; }
        public virtual DbSet<C_BO_backorder_porcentajes> C_BO_backorder_porcentajes { get; set; }
        public virtual DbSet<C_BO_backorder_porcentajes_proteccion> C_BO_backorder_porcentajes_proteccion { get; set; }
        public virtual DbSet<C_BO_backorder_productos> C_BO_backorder_productos { get; set; }
        public virtual DbSet<C_BO_backorder_reemplazo_d> C_BO_backorder_reemplazo_d { get; set; }
        public virtual DbSet<C_BO_backorder_reemplazo_g> C_BO_backorder_reemplazo_g { get; set; }
        public virtual DbSet<C_BO_backorder_remplazos> C_BO_backorder_remplazos { get; set; }
        public virtual DbSet<C_BO_backorder_semanas_calculadas> C_BO_backorder_semanas_calculadas { get; set; }
        public virtual DbSet<C_BO_backorder_sucursales> C_BO_backorder_sucursales { get; set; }
        public virtual DbSet<C_BO_backorder_sucursales_dias> C_BO_backorder_sucursales_dias { get; set; }
        public virtual DbSet<C_BO_backorder_tracking> C_BO_backorder_tracking { get; set; }
        public virtual DbSet<C_bo_calculo> C_bo_calculo { get; set; }
        public virtual DbSet<C_bo_calculo_pe> C_bo_calculo_pe { get; set; }
        public virtual DbSet<C_BO_desvios> C_BO_desvios { get; set; }
        public virtual DbSet<C_BO_desvios_detalle> C_BO_desvios_detalle { get; set; }
        public virtual DbSet<C_BO_dia_inicio> C_BO_dia_inicio { get; set; }
        public virtual DbSet<C_BO_dia_inicio_detalle> C_BO_dia_inicio_detalle { get; set; }
        public virtual DbSet<C_bo_diafestivo_ap> C_bo_diafestivo_ap { get; set; }
        public virtual DbSet<C_BO_dias> C_BO_dias { get; set; }
        public virtual DbSet<C_BO_dias_anios> C_BO_dias_anios { get; set; }
        public virtual DbSet<C_BO_dias_festivos> C_BO_dias_festivos { get; set; }
        public virtual DbSet<C_bo_diasfestivos> C_bo_diasfestivos { get; set; }
        public virtual DbSet<C_bo_g> C_bo_g { get; set; }
        public virtual DbSet<C_BO_historico_detalle> C_BO_historico_detalle { get; set; }
        public virtual DbSet<C_BO_historico_maestro> C_BO_historico_maestro { get; set; }
        public virtual DbSet<C_BO_insumos_embalajes> C_BO_insumos_embalajes { get; set; }
        public virtual DbSet<C_BO_meses_tipo> C_BO_meses_tipo { get; set; }
        public virtual DbSet<C_bo_mov_estatus> C_bo_mov_estatus { get; set; }
        public virtual DbSet<C_bo_mov_tipo> C_bo_mov_tipo { get; set; }
        public virtual DbSet<C_bo_orden> C_bo_orden { get; set; }
        public virtual DbSet<C_bo_porc_df> C_bo_porc_df { get; set; }
        public virtual DbSet<C_BO_rutas> C_BO_rutas { get; set; }
        public virtual DbSet<C_BO_rutas_clasificaciones> C_BO_rutas_clasificaciones { get; set; }
        public virtual DbSet<C_BO_rutas_sucursales> C_BO_rutas_sucursales { get; set; }
        public virtual DbSet<C_bo_semanas_anios_historicos> C_bo_semanas_anios_historicos { get; set; }
        public virtual DbSet<C_bo_semanas_cat> C_bo_semanas_cat { get; set; }
        public virtual DbSet<C_bo_semanas_dias> C_bo_semanas_dias { get; set; }
        public virtual DbSet<C_bo_semanas_meses> C_bo_semanas_meses { get; set; }
        public virtual DbSet<C_bo_semanas_no_dias> C_bo_semanas_no_dias { get; set; }
        public virtual DbSet<C_bo_semanas_trans_c1> C_bo_semanas_trans_c1 { get; set; }
        public virtual DbSet<C_bo_semanas_trans_c3> C_bo_semanas_trans_c3 { get; set; }
        public virtual DbSet<C_bo_semanas_trans_f2> C_bo_semanas_trans_f2 { get; set; }
        public virtual DbSet<C_bo_semanas_trans_par> C_bo_semanas_trans_par { get; set; }
        public virtual DbSet<C_bo_semanas_trans_reg> C_bo_semanas_trans_reg { get; set; }
        public virtual DbSet<C_bo_semanas_trans_rp> C_bo_semanas_trans_rp { get; set; }
        public virtual DbSet<C_BO_subrutas> C_BO_subrutas { get; set; }
        public virtual DbSet<C_bo_suc_ir> C_bo_suc_ir { get; set; }
        public virtual DbSet<C_BO_sucursales_dias_semana> C_BO_sucursales_dias_semana { get; set; }
        public virtual DbSet<C_BO_tipos_mes> C_BO_tipos_mes { get; set; }
        public virtual DbSet<C_BO_validador_parametro> C_BO_validador_parametro { get; set; }
        public virtual DbSet<C_BO_ventas_estandar> C_BO_ventas_estandar { get; set; }
        public virtual DbSet<C_BO_VentasDiariasProducto> C_BO_VentasDiariasProducto { get; set; }
        public virtual DbSet<C_bonos_sucursales_d> C_bonos_sucursales_d { get; set; }
        public virtual DbSet<C_bonos_sucursales_g> C_bonos_sucursales_g { get; set; }
        public virtual DbSet<C_bonos_sucursales_g_roles> C_bonos_sucursales_g_roles { get; set; }
        public virtual DbSet<C_caja_comercial_cambio_turno> C_caja_comercial_cambio_turno { get; set; }
        public virtual DbSet<C_caja_comercial_movimientos> C_caja_comercial_movimientos { get; set; }
        public virtual DbSet<C_caja_usuario> C_caja_usuario { get; set; }
        public virtual DbSet<C_cajas_cambio_turno> C_cajas_cambio_turno { get; set; }
        public virtual DbSet<C_cajas_g> C_cajas_g { get; set; }
        public virtual DbSet<C_cajas_movimientos> C_cajas_movimientos { get; set; }
        public virtual DbSet<C_cajas_movimientos_cancelados> C_cajas_movimientos_cancelados { get; set; }
        public virtual DbSet<C_cajas_nombres> C_cajas_nombres { get; set; }
        public virtual DbSet<C_cajas_retiro_dias> C_cajas_retiro_dias { get; set; }
        public virtual DbSet<C_cajas_retiro_valores> C_cajas_retiro_valores { get; set; }
        public virtual DbSet<C_cajas_sucursales> C_cajas_sucursales { get; set; }
        public virtual DbSet<C_cajas_sucursales_comercial> C_cajas_sucursales_comercial { get; set; }
        public virtual DbSet<C_cajas_tipo_mov> C_cajas_tipo_mov { get; set; }
        public virtual DbSet<C_cajas_tipo_mov_sucursales> C_cajas_tipo_mov_sucursales { get; set; }
        public virtual DbSet<C_CFDI_Cancelaciones_LOGS> C_CFDI_Cancelaciones_LOGS { get; set; }
        public virtual DbSet<C_CFDI_CancelacionesFactura> C_CFDI_CancelacionesFactura { get; set; }
        public virtual DbSet<C_CFDI_Clasi_Promos> C_CFDI_Clasi_Promos { get; set; }
        public virtual DbSet<C_CFDI_Cliente> C_CFDI_Cliente { get; set; }
        public virtual DbSet<C_CFDI_Empresas_Datos_Fis> C_CFDI_Empresas_Datos_Fis { get; set; }
        public virtual DbSet<C_CFDI_Estados> C_CFDI_Estados { get; set; }
        public virtual DbSet<C_CFDI_EstadosMunicipios> C_CFDI_EstadosMunicipios { get; set; }
        public virtual DbSet<C_CFDI_Estatus_Logs> C_CFDI_Estatus_Logs { get; set; }
        public virtual DbSet<C_CFDI_Factura_Estatus> C_CFDI_Factura_Estatus { get; set; }
        public virtual DbSet<C_CFDI_Facturas> C_CFDI_Facturas { get; set; }
        public virtual DbSet<C_CFDI_Formas_Pago> C_CFDI_Formas_Pago { get; set; }
        public virtual DbSet<C_cfdi_informacion> C_cfdi_informacion { get; set; }
        public virtual DbSet<C_CFDI_LOGS> C_CFDI_LOGS { get; set; }
        public virtual DbSet<C_CFDI_Marcas_Alias> C_CFDI_Marcas_Alias { get; set; }
        public virtual DbSet<C_CFDI_Sucursal_Consec> C_CFDI_Sucursal_Consec { get; set; }
        public virtual DbSet<C_CFDI_Sucursales_CodigoPostal> C_CFDI_Sucursales_CodigoPostal { get; set; }
        public virtual DbSet<C_ciudades> C_ciudades { get; set; }
        public virtual DbSet<C_ciudades_call> C_ciudades_call { get; set; }
        public virtual DbSet<C_clientes> C_clientes { get; set; }
        public virtual DbSet<C_clientes_direccion> C_clientes_direccion { get; set; }
        public virtual DbSet<C_clientes_telefono> C_clientes_telefono { get; set; }
        public virtual DbSet<C_cobranza_corte_d> C_cobranza_corte_d { get; set; }
        public virtual DbSet<C_cobranza_corte_g> C_cobranza_corte_g { get; set; }
        public virtual DbSet<C_cobranza_movs> C_cobranza_movs { get; set; }
        public virtual DbSet<C_cobranza_tabulador> C_cobranza_tabulador { get; set; }
        public virtual DbSet<C_cobranza_tipo_movimientos> C_cobranza_tipo_movimientos { get; set; }
        public virtual DbSet<C_cobranza_tipo_status> C_cobranza_tipo_status { get; set; }
        public virtual DbSet<C_colonias_mx> C_colonias_mx { get; set; }
        public virtual DbSet<C_comisiones_comercial> C_comisiones_comercial { get; set; }
        public virtual DbSet<C_comisiones_productos> C_comisiones_productos { get; set; }
        public virtual DbSet<C_compras_destinos> C_compras_destinos { get; set; }
        public virtual DbSet<C_compras_estatus> C_compras_estatus { get; set; }
        public virtual DbSet<C_compras_firmantes> C_compras_firmantes { get; set; }
        public virtual DbSet<C_compras_hoja> C_compras_hoja { get; set; }
        public virtual DbSet<C_compras_leyendas_condiciones> C_compras_leyendas_condiciones { get; set; }
        public virtual DbSet<C_compras_mes_trans_c1> C_compras_mes_trans_c1 { get; set; }
        public virtual DbSet<C_compras_mes_trans_c3> C_compras_mes_trans_c3 { get; set; }
        public virtual DbSet<C_compras_mes_trans_f2> C_compras_mes_trans_f2 { get; set; }
        public virtual DbSet<C_compras_mov_almacen> C_compras_mov_almacen { get; set; }
        public virtual DbSet<C_compras_orden> C_compras_orden { get; set; }
        public virtual DbSet<C_compras_orden_articulos> C_compras_orden_articulos { get; set; }
        public virtual DbSet<C_conciliacion_cobro_d> C_conciliacion_cobro_d { get; set; }
        public virtual DbSet<C_conciliacion_cobro_g> C_conciliacion_cobro_g { get; set; }
        public virtual DbSet<C_costos_domicilio> C_costos_domicilio { get; set; }
        public virtual DbSet<C_cp_mexico> C_cp_mexico { get; set; }
        public virtual DbSet<C_credito_distribuidor_empleados> C_credito_distribuidor_empleados { get; set; }
        public virtual DbSet<C_credito_estatus_cuenta> C_credito_estatus_cuenta { get; set; }
        public virtual DbSet<C_credito_movimientos_wallet> C_credito_movimientos_wallet { get; set; }
        public virtual DbSet<C_credito_tipos> C_credito_tipos { get; set; }
        public virtual DbSet<C_cuenta_status> C_cuenta_status { get; set; }
        public virtual DbSet<C_Delivery_a_new_register> C_Delivery_a_new_register { get; set; }
        public virtual DbSet<C_Delivery_App> C_Delivery_App { get; set; }
        public virtual DbSet<C_Delivery_Asignacion_Pedidos_Repartidores> C_Delivery_Asignacion_Pedidos_Repartidores { get; set; }
        public virtual DbSet<C_Delivery_Calles> C_Delivery_Calles { get; set; }
        public virtual DbSet<C_Delivery_Categorias> C_Delivery_Categorias { get; set; }
        public virtual DbSet<C_Delivery_Ciudad> C_Delivery_Ciudad { get; set; }
        public virtual DbSet<C_Delivery_Cliente_Direcciones> C_Delivery_Cliente_Direcciones { get; set; }
        public virtual DbSet<C_Delivery_Clientes> C_Delivery_Clientes { get; set; }
        public virtual DbSet<C_Delivery_Colonias> C_Delivery_Colonias { get; set; }
        public virtual DbSet<C_Delivery_Colonias_Tipo> C_Delivery_Colonias_Tipo { get; set; }
        public virtual DbSet<C_Delivery_Colores_Vehiculos> C_Delivery_Colores_Vehiculos { get; set; }
        public virtual DbSet<C_Delivery_Comision_Zpidi> C_Delivery_Comision_Zpidi { get; set; }
        public virtual DbSet<C_Delivery_Comisiones> C_Delivery_Comisiones { get; set; }
        public virtual DbSet<C_Delivery_Conversations> C_Delivery_Conversations { get; set; }
        public virtual DbSet<C_Delivery_CorreosTemplates> C_Delivery_CorreosTemplates { get; set; }
        public virtual DbSet<C_Delivery_Costo_Envio> C_Delivery_Costo_Envio { get; set; }
        public virtual DbSet<C_Delivery_Domicilios> C_Delivery_Domicilios { get; set; }
        public virtual DbSet<C_Delivery_empresas> C_Delivery_empresas { get; set; }
        public virtual DbSet<C_Delivery_Empresas_Categorias> C_Delivery_Empresas_Categorias { get; set; }
        public virtual DbSet<C_Delivery_Empresas_Politicas> C_Delivery_Empresas_Politicas { get; set; }
        public virtual DbSet<C_Delivery_Estados> C_Delivery_Estados { get; set; }
        public virtual DbSet<C_Delivery_estatus_semaforo> C_Delivery_estatus_semaforo { get; set; }
        public virtual DbSet<C_Delivery_estatus_semaforo_alias> C_Delivery_estatus_semaforo_alias { get; set; }
        public virtual DbSet<C_Delivery_estatus_semaforo_log> C_Delivery_estatus_semaforo_log { get; set; }
        public virtual DbSet<C_Delivery_fechas_nacimiento> C_Delivery_fechas_nacimiento { get; set; }
        public virtual DbSet<C_Delivery_Generos> C_Delivery_Generos { get; set; }
        public virtual DbSet<C_Delivery_Img_Productos> C_Delivery_Img_Productos { get; set; }
        public virtual DbSet<C_Delivery_Logos_App> C_Delivery_Logos_App { get; set; }
        public virtual DbSet<C_Delivery_Marca_Comision_Pagos> C_Delivery_Marca_Comision_Pagos { get; set; }
        public virtual DbSet<C_Delivery_Marca_Empresas> C_Delivery_Marca_Empresas { get; set; }
        public virtual DbSet<C_Delivery_Marcas> C_Delivery_Marcas { get; set; }
        public virtual DbSet<C_Delivery_Menuappbar> C_Delivery_Menuappbar { get; set; }
        public virtual DbSet<C_Delivery_Menuappbar_Modules> C_Delivery_Menuappbar_Modules { get; set; }
        public virtual DbSet<C_Delivery_Menuappbar_ModulesWeb> C_Delivery_Menuappbar_ModulesWeb { get; set; }
        public virtual DbSet<C_Delivery_Menuappbar_Perfil_Modulo> C_Delivery_Menuappbar_Perfil_Modulo { get; set; }
        public virtual DbSet<C_Delivery_Menuappbar_SubModules> C_Delivery_Menuappbar_SubModules { get; set; }
        public virtual DbSet<C_Delivery_Menuappbar_SubModules_Permisos> C_Delivery_Menuappbar_SubModules_Permisos { get; set; }
        public virtual DbSet<C_Delivery_Notificacion_entregas> C_Delivery_Notificacion_entregas { get; set; }
        public virtual DbSet<C_Delivery_Notificacion_mensaje> C_Delivery_Notificacion_mensaje { get; set; }
        public virtual DbSet<C_Delivery_Notificacion_msg_auto> C_Delivery_Notificacion_msg_auto { get; set; }
        public virtual DbSet<C_Delivery_Notificacion_tipo> C_Delivery_Notificacion_tipo { get; set; }
        public virtual DbSet<C_Delivery_Ordenes_Bloqueo> C_Delivery_Ordenes_Bloqueo { get; set; }
        public virtual DbSet<C_Delivery_Ordenes_Pagos> C_Delivery_Ordenes_Pagos { get; set; }
        public virtual DbSet<C_Delivery_Ordenes_Pagos_Formas> C_Delivery_Ordenes_Pagos_Formas { get; set; }
        public virtual DbSet<C_Delivery_Ordenes_Tracking_Asignaciones> C_Delivery_Ordenes_Tracking_Asignaciones { get; set; }
        public virtual DbSet<C_Delivery_OrderDetail> C_Delivery_OrderDetail { get; set; }
        public virtual DbSet<C_Delivery_Orders> C_Delivery_Orders { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Impuestos> C_Delivery_Pagos_Impuestos { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Plataformas> C_Delivery_Pagos_Plataformas { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Dispersion_Plataformas> C_Delivery_Pagos_Programados_Dispersion_Plataformas { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Repartidores> C_Delivery_Pagos_Repartidores { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Servicio_Zpidi> C_Delivery_Pagos_Servicio_Zpidi { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Status> C_Delivery_Pagos_Status { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Tipos> C_Delivery_Pagos_Tipos { get; set; }
        public virtual DbSet<C_Delivery_Pais> C_Delivery_Pais { get; set; }
        public virtual DbSet<C_Delivery_Pais_Impuestos> C_Delivery_Pais_Impuestos { get; set; }
        public virtual DbSet<C_Delivery_Pais_Moneda> C_Delivery_Pais_Moneda { get; set; }
        public virtual DbSet<C_Delivery_Parametros> C_Delivery_Parametros { get; set; }
        public virtual DbSet<C_Delivery_Perfiles> C_Delivery_Perfiles { get; set; }
        public virtual DbSet<C_Delivery_Plataformas> C_Delivery_Plataformas { get; set; }
        public virtual DbSet<C_Delivery_Plataformas_Configuracion> C_Delivery_Plataformas_Configuracion { get; set; }
        public virtual DbSet<C_Delivery_Pre_Orders> C_Delivery_Pre_Orders { get; set; }
        public virtual DbSet<C_Delivery_Pronosticos_Pagos> C_Delivery_Pronosticos_Pagos { get; set; }
        public virtual DbSet<C_Delivery_Pronosticos_PagosDetail> C_Delivery_Pronosticos_PagosDetail { get; set; }
        public virtual DbSet<C_Delivery_Rate> C_Delivery_Rate { get; set; }
        public virtual DbSet<C_Delivery_Reasons> C_Delivery_Reasons { get; set; }
        public virtual DbSet<C_Delivery_Repartidor_Vehiculo> C_Delivery_Repartidor_Vehiculo { get; set; }
        public virtual DbSet<C_Delivery_Repartidores> C_Delivery_Repartidores { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Docs> C_Delivery_Repartidores_Docs { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Documentacion> C_Delivery_Repartidores_Documentacion { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Documentacion_Tipo> C_Delivery_Repartidores_Documentacion_Tipo { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Empresas_Sucursales> C_Delivery_Repartidores_Empresas_Sucursales { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Ordenes> C_Delivery_Repartidores_Ordenes { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Ordenes_Reportes> C_Delivery_Repartidores_Ordenes_Reportes { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_p> C_Delivery_Repartidores_p { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Pagos_Conceptos> C_Delivery_Repartidores_Pagos_Conceptos { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Solicitud> C_Delivery_Repartidores_Solicitud { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Solicitudes> C_Delivery_Repartidores_Solicitudes { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Status> C_Delivery_Repartidores_Status { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Ubicaciones> C_Delivery_Repartidores_Ubicaciones { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Vehiculos> C_Delivery_Repartidores_Vehiculos { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Vehiculos_Tipos> C_Delivery_Repartidores_Vehiculos_Tipos { get; set; }
        public virtual DbSet<C_Delivery_RepartidoresColonias> C_Delivery_RepartidoresColonias { get; set; }
        public virtual DbSet<C_Delivery_Semaforo> C_Delivery_Semaforo { get; set; }
        public virtual DbSet<C_Delivery_Splash_Images> C_Delivery_Splash_Images { get; set; }
        public virtual DbSet<C_Delivery_StartOrders> C_Delivery_StartOrders { get; set; }
        public virtual DbSet<C_Delivery_Status> C_Delivery_Status { get; set; }
        public virtual DbSet<C_Delivery_Sucursales_Direcciones> C_Delivery_Sucursales_Direcciones { get; set; }
        public virtual DbSet<C_Delivery_sucursales_gps> C_Delivery_sucursales_gps { get; set; }
        public virtual DbSet<C_Delivery_Tipos_Cuotas> C_Delivery_Tipos_Cuotas { get; set; }
        public virtual DbSet<C_Delivery_Trafico_Semaforos> C_Delivery_Trafico_Semaforos { get; set; }
        public virtual DbSet<C_Delivery_Usuarios_Imagen> C_Delivery_Usuarios_Imagen { get; set; }
        public virtual DbSet<C_Delivery_Vehiculo_p> C_Delivery_Vehiculo_p { get; set; }
        public virtual DbSet<C_Delivery_Zona_Gps> C_Delivery_Zona_Gps { get; set; }
        public virtual DbSet<C_Delivery_Zonas_Cuadrantes> C_Delivery_Zonas_Cuadrantes { get; set; }
        public virtual DbSet<C_Delivery_Zonas_Reparto> C_Delivery_Zonas_Reparto { get; set; }
        public virtual DbSet<C_Delivery_Zonas_Reparto_Perimetros> C_Delivery_Zonas_Reparto_Perimetros { get; set; }
        public virtual DbSet<C_dias_semana> C_dias_semana { get; set; }
        public virtual DbSet<C_direcciones> C_direcciones { get; set; }
        public virtual DbSet<C_direcciones_3_> C_direcciones_3_ { get; set; }
        public virtual DbSet<C_direcciones_mx> C_direcciones_mx { get; set; }
        public virtual DbSet<C_direcciones_sucursales> C_direcciones_sucursales { get; set; }
        public virtual DbSet<C_dvy_repartidores_dia_descanso> C_dvy_repartidores_dia_descanso { get; set; }
        public virtual DbSet<C_dvy_zonas> C_dvy_zonas { get; set; }
        public virtual DbSet<C_dvy_zonas_repartidores> C_dvy_zonas_repartidores { get; set; }
        public virtual DbSet<C_dvy_zonas_sucursales> C_dvy_zonas_sucursales { get; set; }
        public virtual DbSet<C_empleados> C_empleados { get; set; }
        public virtual DbSet<C_empleados_cargo_motivos> C_empleados_cargo_motivos { get; set; }
        public virtual DbSet<C_empleados_cargos> C_empleados_cargos { get; set; }
        public virtual DbSet<C_empleados_estados> C_empleados_estados { get; set; }
        public virtual DbSet<C_empleados_niveles> C_empleados_niveles { get; set; }
        public virtual DbSet<C_empleados_saldo> C_empleados_saldo { get; set; }
        public virtual DbSet<C_empleados_team_card> C_empleados_team_card { get; set; }
        public virtual DbSet<C_empleados_tipo_sangre> C_empleados_tipo_sangre { get; set; }
        public virtual DbSet<C_empleados_tmp> C_empleados_tmp { get; set; }
        public virtual DbSet<C_empleados_visible> C_empleados_visible { get; set; }
        public virtual DbSet<C_empresas> C_empresas { get; set; }
        public virtual DbSet<C_empresas_sucursales> C_empresas_sucursales { get; set; }
        public virtual DbSet<C_empresas_tipo> C_empresas_tipo { get; set; }
        public virtual DbSet<C_encuesta_preguntas> C_encuesta_preguntas { get; set; }
        public virtual DbSet<C_encuesta_preguntas_subcategoria> C_encuesta_preguntas_subcategoria { get; set; }
        public virtual DbSet<C_encuesta_respuestas> C_encuesta_respuestas { get; set; }
        public virtual DbSet<C_encuesta_rol> C_encuesta_rol { get; set; }
        public virtual DbSet<C_encuestas> C_encuestas { get; set; }
        public virtual DbSet<C_encuestas_registro_d> C_encuestas_registro_d { get; set; }
        public virtual DbSet<C_encuestas_registro_g> C_encuestas_registro_g { get; set; }
        public virtual DbSet<C_encuestas_sucursal> C_encuestas_sucursal { get; set; }
        public virtual DbSet<C_entidades> C_entidades { get; set; }
        public virtual DbSet<C_equipo_sucursal> C_equipo_sucursal { get; set; }
        public virtual DbSet<C_estados> C_estados { get; set; }
        public virtual DbSet<C_estados_call> C_estados_call { get; set; }
        public virtual DbSet<C_eventos> C_eventos { get; set; }
        public virtual DbSet<C_facturas> C_facturas { get; set; }
        public virtual DbSet<C_frases> C_frases { get; set; }
        public virtual DbSet<C_grupo_aplica_operacion> C_grupo_aplica_operacion { get; set; }
        public virtual DbSet<C_grupo_difusion> C_grupo_difusion { get; set; }
        public virtual DbSet<C_grupo_productos_codigos> C_grupo_productos_codigos { get; set; }
        public virtual DbSet<C_grupo_productos_codigos_movs> C_grupo_productos_codigos_movs { get; set; }
        public virtual DbSet<C_grupo_productos_codigos_telefonos> C_grupo_productos_codigos_telefonos { get; set; }
        public virtual DbSet<C_grupo_productos_d> C_grupo_productos_d { get; set; }
        public virtual DbSet<C_grupo_productos_destino_social> C_grupo_productos_destino_social { get; set; }
        public virtual DbSet<C_grupo_productos_destino_telefonos> C_grupo_productos_destino_telefonos { get; set; }
        public virtual DbSet<C_grupo_productos_dias> C_grupo_productos_dias { get; set; }
        public virtual DbSet<C_grupo_productos_g> C_grupo_productos_g { get; set; }
        public virtual DbSet<C_grupo_productos_marcas> C_grupo_productos_marcas { get; set; }
        public virtual DbSet<C_grupo_productos_prods> C_grupo_productos_prods { get; set; }
        public virtual DbSet<C_grupo_productos_subclases> C_grupo_productos_subclases { get; set; }
        public virtual DbSet<C_grupo_productos_sucursales> C_grupo_productos_sucursales { get; set; }
        public virtual DbSet<C_grupo_productos_tipos> C_grupo_productos_tipos { get; set; }
        public virtual DbSet<C_guias> C_guias { get; set; }
        public virtual DbSet<C_HD_area> C_HD_area { get; set; }
        public virtual DbSet<C_HD_Categoria> C_HD_Categoria { get; set; }
        public virtual DbSet<C_HD_categorias_prioridades> C_HD_categorias_prioridades { get; set; }
        public virtual DbSet<C_HD_CorreosDepartamentos> C_HD_CorreosDepartamentos { get; set; }
        public virtual DbSet<C_HD_departamentos> C_HD_departamentos { get; set; }
        public virtual DbSet<C_HD_evidencia_reporte> C_HD_evidencia_reporte { get; set; }
        public virtual DbSet<C_HD_evidencia_solucion> C_HD_evidencia_solucion { get; set; }
        public virtual DbSet<C_HD_evidencia_ticket> C_HD_evidencia_ticket { get; set; }
        public virtual DbSet<C_HD_grupos_especialistas> C_HD_grupos_especialistas { get; set; }
        public virtual DbSet<C_HD_grupos_personas> C_HD_grupos_personas { get; set; }
        public virtual DbSet<C_HD_modulos> C_HD_modulos { get; set; }
        public virtual DbSet<C_HD_modulos_sub> C_HD_modulos_sub { get; set; }
        public virtual DbSet<C_HD_modulos_sub_permisos> C_HD_modulos_sub_permisos { get; set; }
        public virtual DbSet<C_HD_soluciones> C_HD_soluciones { get; set; }
        public virtual DbSet<C_HD_status_ticket> C_HD_status_ticket { get; set; }
        public virtual DbSet<C_HD_subArea> C_HD_subArea { get; set; }
        public virtual DbSet<C_HD_Ticket> C_HD_Ticket { get; set; }
        public virtual DbSet<C_HD_ticket_detalle> C_HD_ticket_detalle { get; set; }
        public virtual DbSet<C_HD_tipo_vista> C_HD_tipo_vista { get; set; }
        public virtual DbSet<C_HD_usuario_tipo> C_HD_usuario_tipo { get; set; }
        public virtual DbSet<C_HD_usuario_tipo_roles> C_HD_usuario_tipo_roles { get; set; }
        public virtual DbSet<C_HD_valoracion> C_HD_valoracion { get; set; }
        public virtual DbSet<C_horas_dia> C_horas_dia { get; set; }
        public virtual DbSet<C_impresion_log> C_impresion_log { get; set; }
        public virtual DbSet<C_impresion_parametros> C_impresion_parametros { get; set; }
        public virtual DbSet<C_impresion_sucursales> C_impresion_sucursales { get; set; }
        public virtual DbSet<C_impresion_tipo_marca> C_impresion_tipo_marca { get; set; }
        public virtual DbSet<C_impresion_tipo_sucursal> C_impresion_tipo_sucursal { get; set; }
        public virtual DbSet<C_impresion_tipos> C_impresion_tipos { get; set; }
        public virtual DbSet<C_impuesto_producto> C_impuesto_producto { get; set; }
        public virtual DbSet<C_impuestos> C_impuestos { get; set; }
        public virtual DbSet<C_Indicadores_Tiempos_Estandar> C_Indicadores_Tiempos_Estandar { get; set; }
        public virtual DbSet<C_insumo_cat> C_insumo_cat { get; set; }
        public virtual DbSet<C_insumo_cat_log_d> C_insumo_cat_log_d { get; set; }
        public virtual DbSet<C_insumo_cat_log_g> C_insumo_cat_log_g { get; set; }
        public virtual DbSet<C_insumo_clasificacion> C_insumo_clasificacion { get; set; }
        public virtual DbSet<C_insumo_mov_log> C_insumo_mov_log { get; set; }
        public virtual DbSet<C_insumo_mov_masivo> C_insumo_mov_masivo { get; set; }
        public virtual DbSet<C_insumo_mov_masivo_d> C_insumo_mov_masivo_d { get; set; }
        public virtual DbSet<C_insumo_mov_status> C_insumo_mov_status { get; set; }
        public virtual DbSet<C_insumo_mov_suc_d> C_insumo_mov_suc_d { get; set; }
        public virtual DbSet<C_insumo_mov_suc_g> C_insumo_mov_suc_g { get; set; }
        public virtual DbSet<C_insumo_presentacion> C_insumo_presentacion { get; set; }
        public virtual DbSet<C_insumo_subclasificacion> C_insumo_subclasificacion { get; set; }
        public virtual DbSet<C_insumo_sucursal> C_insumo_sucursal { get; set; }
        public virtual DbSet<C_insumo_tipo_empaque> C_insumo_tipo_empaque { get; set; }
        public virtual DbSet<C_insumo_tipo_envase> C_insumo_tipo_envase { get; set; }
        public virtual DbSet<C_insumo_tipo_mov> C_insumo_tipo_mov { get; set; }
        public virtual DbSet<C_insumo_tipo_mov_clasificacion> C_insumo_tipo_mov_clasificacion { get; set; }
        public virtual DbSet<C_insumo_tipo_mov_clasificacion_marca> C_insumo_tipo_mov_clasificacion_marca { get; set; }
        public virtual DbSet<C_insumo_tipo_mov_rol> C_insumo_tipo_mov_rol { get; set; }
        public virtual DbSet<C_insumo_tipos_backorder> C_insumo_tipos_backorder { get; set; }
        public virtual DbSet<C_insumo_tipos_backorder_nombres> C_insumo_tipos_backorder_nombres { get; set; }
        public virtual DbSet<C_insumos_criticos> C_insumos_criticos { get; set; }
        public virtual DbSet<C_insumos_criticos_dias_inventario> C_insumos_criticos_dias_inventario { get; set; }
        public virtual DbSet<C_insumos_criticos_tipos> C_insumos_criticos_tipos { get; set; }
        public virtual DbSet<C_inventario_ingredientada> C_inventario_ingredientada { get; set; }
        public virtual DbSet<C_inventario_suc_d> C_inventario_suc_d { get; set; }
        public virtual DbSet<C_inventario_suc_g> C_inventario_suc_g { get; set; }
        public virtual DbSet<C_inventario_sucursal_tipo> C_inventario_sucursal_tipo { get; set; }
        public virtual DbSet<C_log_acciones> C_log_acciones { get; set; }
        public virtual DbSet<C_log_autorizaciones_nip> C_log_autorizaciones_nip { get; set; }
        public virtual DbSet<C_log_errores_sistema> C_log_errores_sistema { get; set; }
        public virtual DbSet<C_log_modificaciones_g> C_log_modificaciones_g { get; set; }
        public virtual DbSet<C_log_pedidos_externos> C_log_pedidos_externos { get; set; }
        public virtual DbSet<C_log_pedidos_repartidor> C_log_pedidos_repartidor { get; set; }
        public virtual DbSet<C_log_servicio_delivery> C_log_servicio_delivery { get; set; }
        public virtual DbSet<C_log_solicitudes_server> C_log_solicitudes_server { get; set; }
        public virtual DbSet<C_log_versiones> C_log_versiones { get; set; }
        public virtual DbSet<C_log_versiones_detalle> C_log_versiones_detalle { get; set; }
        public virtual DbSet<C_login_empleados> C_login_empleados { get; set; }
        public virtual DbSet<C_marcas_datos_fiscales> C_marcas_datos_fiscales { get; set; }
        public virtual DbSet<C_marcas_direcciones> C_marcas_direcciones { get; set; }
        public virtual DbSet<C_marcas_g> C_marcas_g { get; set; }
        public virtual DbSet<C_marcas_sociedades> C_marcas_sociedades { get; set; }
        public virtual DbSet<C_medios> C_medios { get; set; }
        public virtual DbSet<C_mensajeria> C_mensajeria { get; set; }
        public virtual DbSet<C_mensajeria_destinatarios> C_mensajeria_destinatarios { get; set; }
        public virtual DbSet<C_menu> C_menu { get; set; }
        public virtual DbSet<C_menu_secciones> C_menu_secciones { get; set; }
        public virtual DbSet<C_mesa_tipo> C_mesa_tipo { get; set; }
        public virtual DbSet<C_mesas> C_mesas { get; set; }
        public virtual DbSet<C_mesas_status> C_mesas_status { get; set; }
        public virtual DbSet<C_mesas_sucursales> C_mesas_sucursales { get; set; }
        public virtual DbSet<C_microsip_bajas_log> C_microsip_bajas_log { get; set; }
        public virtual DbSet<C_microsip_cambio_depa_cajeros_estatus> C_microsip_cambio_depa_cajeros_estatus { get; set; }
        public virtual DbSet<C_microsip_cambios_empleados> C_microsip_cambios_empleados { get; set; }
        public virtual DbSet<C_microsip_dptos_sucursales> C_microsip_dptos_sucursales { get; set; }
        public virtual DbSet<C_microsip_empleados_cambio_depa_cajeros> C_microsip_empleados_cambio_depa_cajeros { get; set; }
        public virtual DbSet<C_microsip_empleados_no_registrados> C_microsip_empleados_no_registrados { get; set; }
        public virtual DbSet<C_microsip_puestos_roles> C_microsip_puestos_roles { get; set; }
        public virtual DbSet<C_modulos> C_modulos { get; set; }
        public virtual DbSet<C_modulos_sub> C_modulos_sub { get; set; }
        public virtual DbSet<C_modulos_sub_permisos> C_modulos_sub_permisos { get; set; }
        public virtual DbSet<C_modulos_tipo_permisos> C_modulos_tipo_permisos { get; set; }
        public virtual DbSet<C_municipios> C_municipios { get; set; }
        public virtual DbSet<C_notificaciones_mensajes> C_notificaciones_mensajes { get; set; }
        public virtual DbSet<C_notificaciones_subtipos> C_notificaciones_subtipos { get; set; }
        public virtual DbSet<C_notificaciones_tipo> C_notificaciones_tipo { get; set; }
        public virtual DbSet<C_pago_tipo> C_pago_tipo { get; set; }
        public virtual DbSet<C_paises> C_paises { get; set; }
        public virtual DbSet<C_pantallas_web> C_pantallas_web { get; set; }
        public virtual DbSet<C_parametro_ingredientadas> C_parametro_ingredientadas { get; set; }
        public virtual DbSet<C_parametros> C_parametros { get; set; }
        public virtual DbSet<C_parametros_configuracion> C_parametros_configuracion { get; set; }
        public virtual DbSet<C_parametros_empresa> C_parametros_empresa { get; set; }
        public virtual DbSet<C_parametros_marcas> C_parametros_marcas { get; set; }
        public virtual DbSet<C_parametros_sucursales> C_parametros_sucursales { get; set; }
        public virtual DbSet<C_pedido_comercial_descuentos> C_pedido_comercial_descuentos { get; set; }
        public virtual DbSet<C_pedido_tiempo_recepcion> C_pedido_tiempo_recepcion { get; set; }
        public virtual DbSet<C_pedidos> C_pedidos { get; set; }
        public virtual DbSet<C_pedidos_comercial> C_pedidos_comercial { get; set; }
        public virtual DbSet<C_pedidos_comercial_d> C_pedidos_comercial_d { get; set; }
        public virtual DbSet<C_pedidos_d> C_pedidos_d { get; set; }
        public virtual DbSet<C_pedidos_descuentos> C_pedidos_descuentos { get; set; }
        public virtual DbSet<C_pedidos_descuentos_comercial> C_pedidos_descuentos_comercial { get; set; }
        public virtual DbSet<C_pedidos_empleados> C_pedidos_empleados { get; set; }
        public virtual DbSet<C_pedidos_productos_cancelados> C_pedidos_productos_cancelados { get; set; }
        public virtual DbSet<C_pedidos_propinas> C_pedidos_propinas { get; set; }
        public virtual DbSet<C_pedidos_ticket_status> C_pedidos_ticket_status { get; set; }
        public virtual DbSet<C_pedidos_tipo> C_pedidos_tipo { get; set; }
        public virtual DbSet<C_pedidos_vehiculo> C_pedidos_vehiculo { get; set; }
        public virtual DbSet<C_plan_comercial> C_plan_comercial { get; set; }
        public virtual DbSet<C_plan_comercial_d> C_plan_comercial_d { get; set; }
        public virtual DbSet<C_plan_comercial_facturacion> C_plan_comercial_facturacion { get; set; }
        public virtual DbSet<C_plan_comercial_facturacion_d> C_plan_comercial_facturacion_d { get; set; }
        public virtual DbSet<C_plan_comercial_productos> C_plan_comercial_productos { get; set; }
        public virtual DbSet<C_plan_comercial_programacion> C_plan_comercial_programacion { get; set; }
        public virtual DbSet<C_pos_caja_cambioturno> C_pos_caja_cambioturno { get; set; }
        public virtual DbSet<C_pos_caja_cambioturno_insumos> C_pos_caja_cambioturno_insumos { get; set; }
        public virtual DbSet<C_pos_caja_movs> C_pos_caja_movs { get; set; }
        public virtual DbSet<C_preguntas_web> C_preguntas_web { get; set; }
        public virtual DbSet<C_presentaciones> C_presentaciones { get; set; }
        public virtual DbSet<C_produccion_acciones_previas> C_produccion_acciones_previas { get; set; }
        public virtual DbSet<C_produccion_generada> C_produccion_generada { get; set; }
        public virtual DbSet<C_produccion_generada_d> C_produccion_generada_d { get; set; }
        public virtual DbSet<C_producto_base_tipo> C_producto_base_tipo { get; set; }
        public virtual DbSet<C_producto_clasificacion> C_producto_clasificacion { get; set; }
        public virtual DbSet<C_producto_clasificacion_base> C_producto_clasificacion_base { get; set; }
        public virtual DbSet<C_producto_presentacion> C_producto_presentacion { get; set; }
        public virtual DbSet<C_producto_subclasificacion> C_producto_subclasificacion { get; set; }
        public virtual DbSet<C_producto_tipo> C_producto_tipo { get; set; }
        public virtual DbSet<C_productos_cat> C_productos_cat { get; set; }
        public virtual DbSet<C_productos_cat_log_d> C_productos_cat_log_d { get; set; }
        public virtual DbSet<C_productos_cat_log_g> C_productos_cat_log_g { get; set; }
        public virtual DbSet<C_productos_clase> C_productos_clase { get; set; }
        public virtual DbSet<C_productos_especialidades> C_productos_especialidades { get; set; }
        public virtual DbSet<C_productos_plataforma_d> C_productos_plataforma_d { get; set; }
        public virtual DbSet<C_productos_plataforma_g> C_productos_plataforma_g { get; set; }
        public virtual DbSet<C_productos_precios> C_productos_precios { get; set; }
        public virtual DbSet<C_productos_sucursal> C_productos_sucursal { get; set; }
        public virtual DbSet<C_rappi_log_tracking> C_rappi_log_tracking { get; set; }
        public virtual DbSet<C_rappi_ordenes_g> C_rappi_ordenes_g { get; set; }
        public virtual DbSet<C_rappi_ordenes_pedidos> C_rappi_ordenes_pedidos { get; set; }
        public virtual DbSet<C_rappi_parametros> C_rappi_parametros { get; set; }
        public virtual DbSet<C_rappi_productos> C_rappi_productos { get; set; }
        public virtual DbSet<C_rappi_sucursales> C_rappi_sucursales { get; set; }
        public virtual DbSet<C_rappi_tipo_status> C_rappi_tipo_status { get; set; }
        public virtual DbSet<C_recepcion_pedido> C_recepcion_pedido { get; set; }
        public virtual DbSet<C_recetas> C_recetas { get; set; }
        public virtual DbSet<C_recetas_log_d> C_recetas_log_d { get; set; }
        public virtual DbSet<C_Repartidores_Sucursales> C_Repartidores_Sucursales { get; set; }
        public virtual DbSet<C_roles_movimientos> C_roles_movimientos { get; set; }
        public virtual DbSet<C_Semanas_Años> C_Semanas_Años { get; set; }
        public virtual DbSet<C_servicios> C_servicios { get; set; }
        public virtual DbSet<C_servicios_modulos> C_servicios_modulos { get; set; }
        public virtual DbSet<C_servicios_roles> C_servicios_roles { get; set; }
        public virtual DbSet<C_servicios_sucursal> C_servicios_sucursal { get; set; }
        public virtual DbSet<C_sociedades> C_sociedades { get; set; }
        public virtual DbSet<C_sociedades_empresas> C_sociedades_empresas { get; set; }
        public virtual DbSet<C_solicitudes_repartidor> C_solicitudes_repartidor { get; set; }
        public virtual DbSet<C_solicitudes_repartidor_status> C_solicitudes_repartidor_status { get; set; }
        public virtual DbSet<C_status_pedido_recepcion> C_status_pedido_recepcion { get; set; }
        public virtual DbSet<C_subrecetas> C_subrecetas { get; set; }
        public virtual DbSet<C_subrecetas_d> C_subrecetas_d { get; set; }
        public virtual DbSet<C_subzonas> C_subzonas { get; set; }
        public virtual DbSet<C_sucursal_status_motivo> C_sucursal_status_motivo { get; set; }
        public virtual DbSet<C_sucursales> C_sucursales { get; set; }
        public virtual DbSet<C_sucursales_colonias> C_sucursales_colonias { get; set; }
        public virtual DbSet<C_sucursales_config> C_sucursales_config { get; set; }
        public virtual DbSet<C_sucursales_credito> C_sucursales_credito { get; set; }
        public virtual DbSet<C_sucursales_direcciones> C_sucursales_direcciones { get; set; }
        public virtual DbSet<C_sucursales_estatus_credito> C_sucursales_estatus_credito { get; set; }
        public virtual DbSet<C_sucursales_ip> C_sucursales_ip { get; set; }
        public virtual DbSet<C_sucursales_marcas> C_sucursales_marcas { get; set; }
        public virtual DbSet<C_sucursales_masterkey> C_sucursales_masterkey { get; set; }
        public virtual DbSet<C_sucursales_preparadas> C_sucursales_preparadas { get; set; }
        public virtual DbSet<C_sucursales_razones> C_sucursales_razones { get; set; }
        public virtual DbSet<C_sucursales_reparto> C_sucursales_reparto { get; set; }
        public virtual DbSet<C_sucursales_reparto_log> C_sucursales_reparto_log { get; set; }
        public virtual DbSet<C_sucursales_warmer> C_sucursales_warmer { get; set; }
        public virtual DbSet<C_sval_actas_diferencia> C_sval_actas_diferencia { get; set; }
        public virtual DbSet<C_sval_cajeros> C_sval_cajeros { get; set; }
        public virtual DbSet<C_sval_deposito_billetes> C_sval_deposito_billetes { get; set; }
        public virtual DbSet<C_sval_deposito_envases> C_sval_deposito_envases { get; set; }
        public virtual DbSet<C_sval_depositos> C_sval_depositos { get; set; }
        public virtual DbSet<C_sval_empresa_servicios_contratados> C_sval_empresa_servicios_contratados { get; set; }
        public virtual DbSet<C_sval_nominas> C_sval_nominas { get; set; }
        public virtual DbSet<C_sval_nominas_envases> C_sval_nominas_envases { get; set; }
        public virtual DbSet<C_sval_orden_envases> C_sval_orden_envases { get; set; }
        public virtual DbSet<C_sval_ordenes> C_sval_ordenes { get; set; }
        public virtual DbSet<C_sval_servicios> C_sval_servicios { get; set; }
        public virtual DbSet<C_sval_sessiones_captura> C_sval_sessiones_captura { get; set; }
        public virtual DbSet<C_sval_tipo_nominacion> C_sval_tipo_nominacion { get; set; }
        public virtual DbSet<C_TA_Estatus_Transacciones> C_TA_Estatus_Transacciones { get; set; }
        public virtual DbSet<C_TA_LOGS> C_TA_LOGS { get; set; }
        public virtual DbSet<C_TA_Marcas_Comercio> C_TA_Marcas_Comercio { get; set; }
        public virtual DbSet<C_TA_MatchTokens> C_TA_MatchTokens { get; set; }
        public virtual DbSet<C_TA_Pedidos_Transacciones> C_TA_Pedidos_Transacciones { get; set; }
        public virtual DbSet<C_TA_Sucursales_Terminales> C_TA_Sucursales_Terminales { get; set; }
        public virtual DbSet<C_team_card_movs> C_team_card_movs { get; set; }
        public virtual DbSet<C_team_card_tipo_movs> C_team_card_tipo_movs { get; set; }
        public virtual DbSet<C_telefonos> C_telefonos { get; set; }
        public virtual DbSet<C_tickets> C_tickets { get; set; }
        public virtual DbSet<C_tipo_alerta_rol> C_tipo_alerta_rol { get; set; }
        public virtual DbSet<C_tipo_alertas> C_tipo_alertas { get; set; }
        public virtual DbSet<C_tipo_asentamientos> C_tipo_asentamientos { get; set; }
        public virtual DbSet<C_tipo_cierre_comercial> C_tipo_cierre_comercial { get; set; }
        public virtual DbSet<C_tipo_entrega> C_tipo_entrega { get; set; }
        public virtual DbSet<C_tipo_logo> C_tipo_logo { get; set; }
        public virtual DbSet<C_tipo_logo_rol> C_tipo_logo_rol { get; set; }
        public virtual DbSet<C_tipo_recepcion_pedido> C_tipo_recepcion_pedido { get; set; }
        public virtual DbSet<C_tipo_vista> C_tipo_vista { get; set; }
        public virtual DbSet<C_tipos_codigo> C_tipos_codigo { get; set; }
        public virtual DbSet<C_token_parametros> C_token_parametros { get; set; }
        public virtual DbSet<C_tracking_status> C_tracking_status { get; set; }
        public virtual DbSet<C_tracking_status_log> C_tracking_status_log { get; set; }
        public virtual DbSet<C_tracking_tiempos> C_tracking_tiempos { get; set; }
        public virtual DbSet<C_tracking_tiempos_general> C_tracking_tiempos_general { get; set; }
        public virtual DbSet<C_unidades_medida> C_unidades_medida { get; set; }
        public virtual DbSet<C_usuarios_corporativo> C_usuarios_corporativo { get; set; }
        public virtual DbSet<C_usuarios_delivery> C_usuarios_delivery { get; set; }
        public virtual DbSet<C_usuarios_grupos> C_usuarios_grupos { get; set; }
        public virtual DbSet<C_usuarios_mesas> C_usuarios_mesas { get; set; }
        public virtual DbSet<C_usuarios_roles> C_usuarios_roles { get; set; }
        public virtual DbSet<C_usuarios_roles_montos> C_usuarios_roles_montos { get; set; }
        public virtual DbSet<C_usuarios_roles_multi> C_usuarios_roles_multi { get; set; }
        public virtual DbSet<C_usuarios_servicios> C_usuarios_servicios { get; set; }
        public virtual DbSet<C_usuarios_subzonas> C_usuarios_subzonas { get; set; }
        public virtual DbSet<C_usuarios_sucursales> C_usuarios_sucursales { get; set; }
        public virtual DbSet<C_usuarios_sucursales_extra> C_usuarios_sucursales_extra { get; set; }
        public virtual DbSet<C_usuarios_tipo> C_usuarios_tipo { get; set; }
        public virtual DbSet<C_usuarios_turnos> C_usuarios_turnos { get; set; }
        public virtual DbSet<C_usuarios_turnos_comercial> C_usuarios_turnos_comercial { get; set; }
        public virtual DbSet<C_usuarios_zonas> C_usuarios_zonas { get; set; }
        public virtual DbSet<C_ventas_cierre_comercial_g> C_ventas_cierre_comercial_g { get; set; }
        public virtual DbSet<C_ventas_cierre_conceptos> C_ventas_cierre_conceptos { get; set; }
        public virtual DbSet<C_ventas_cierre_d> C_ventas_cierre_d { get; set; }
        public virtual DbSet<C_ventas_cierre_d_cobros> C_ventas_cierre_d_cobros { get; set; }
        public virtual DbSet<C_ventas_cierre_d_cobros_nip> C_ventas_cierre_d_cobros_nip { get; set; }
        public virtual DbSet<C_ventas_cierre_d1> C_ventas_cierre_d1 { get; set; }
        public virtual DbSet<C_ventas_cierre_d2> C_ventas_cierre_d2 { get; set; }
        public virtual DbSet<C_ventas_cierre_d3> C_ventas_cierre_d3 { get; set; }
        public virtual DbSet<C_ventas_cierre_d5> C_ventas_cierre_d5 { get; set; }
        public virtual DbSet<C_ventas_cierre_d6> C_ventas_cierre_d6 { get; set; }
        public virtual DbSet<C_ventas_cierre_g> C_ventas_cierre_g { get; set; }
        public virtual DbSet<C_ventas_cierre_inventario> C_ventas_cierre_inventario { get; set; }
        public virtual DbSet<C_ventas_cierre_tipo> C_ventas_cierre_tipo { get; set; }
        public virtual DbSet<C_ventas_cierre_transito> C_ventas_cierre_transito { get; set; }
        public virtual DbSet<C_ventas_d> C_ventas_d { get; set; }
        public virtual DbSet<C_ventas_drop> C_ventas_drop { get; set; }
        public virtual DbSet<C_ventas_drop_comercial> C_ventas_drop_comercial { get; set; }
        public virtual DbSet<C_ventas_drop_parametros> C_ventas_drop_parametros { get; set; }
        public virtual DbSet<C_ventas_g> C_ventas_g { get; set; }
        public virtual DbSet<C_ventas_i> C_ventas_i { get; set; }
        public virtual DbSet<C_ventas_pagos> C_ventas_pagos { get; set; }
        public virtual DbSet<C_ventas_pagos_comercial> C_ventas_pagos_comercial { get; set; }
        public virtual DbSet<C_ventas_pedido_comercial> C_ventas_pedido_comercial { get; set; }
        public virtual DbSet<C_ventas_pedido_comercial_d> C_ventas_pedido_comercial_d { get; set; }
        public virtual DbSet<C_ventas_status> C_ventas_status { get; set; }
        public virtual DbSet<C_ventas_tipo> C_ventas_tipo { get; set; }
        public virtual DbSet<C_vex_plan_meta> C_vex_plan_meta { get; set; }
        public virtual DbSet<C_vex_plan_meta_b1> C_vex_plan_meta_b1 { get; set; }
        public virtual DbSet<C_vex_plan_meta_b2> C_vex_plan_meta_b2 { get; set; }
        public virtual DbSet<C_vex_plan_meta_b3> C_vex_plan_meta_b3 { get; set; }
        public virtual DbSet<C_vex_plan_meta_g> C_vex_plan_meta_g { get; set; }
        public virtual DbSet<C_vex_plan_meta_mes> C_vex_plan_meta_mes { get; set; }
        public virtual DbSet<C_vex_plan_meta_params> C_vex_plan_meta_params { get; set; }
        public virtual DbSet<C_vex_plan_meta_segmento_semana> C_vex_plan_meta_segmento_semana { get; set; }
        public virtual DbSet<C_warmer_d> C_warmer_d { get; set; }
        public virtual DbSet<C_warmer_g> C_warmer_g { get; set; }
        public virtual DbSet<C_warmer_preparadas> C_warmer_preparadas { get; set; }
        public virtual DbSet<C_warmer_productos> C_warmer_productos { get; set; }
        public virtual DbSet<C_warmer_status> C_warmer_status { get; set; }
        public virtual DbSet<C_warmer_sucursales> C_warmer_sucursales { get; set; }
        public virtual DbSet<C_web_log> C_web_log { get; set; }
        public virtual DbSet<C_zona_almacen_suc> C_zona_almacen_suc { get; set; }
        public virtual DbSet<C_zonas> C_zonas { get; set; }
        public virtual DbSet<C_zonas_almacenaje> C_zonas_almacenaje { get; set; }
        public virtual DbSet<C_zonas_marcas> C_zonas_marcas { get; set; }
        public virtual DbSet<C_zonas_plantas> C_zonas_plantas { get; set; }
        public virtual DbSet<C_zonas_precio> C_zonas_precio { get; set; }
        public virtual DbSet<C_zonas_sucursales> C_zonas_sucursales { get; set; }
        public virtual DbSet<CS_callcenter_cliente> CS_callcenter_cliente { get; set; }
        public virtual DbSet<CS_permisos> CS_permisos { get; set; }
        public virtual DbSet<CS_permisos_asignados> CS_permisos_asignados { get; set; }
        public virtual DbSet<CS_roles> CS_roles { get; set; }
        public virtual DbSet<CS_sesiones_usuarios> CS_sesiones_usuarios { get; set; }
        public virtual DbSet<CS_usuario_login> CS_usuario_login { get; set; }
        public virtual DbSet<CS_usuarios> CS_usuarios { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<M_callcenter_clientes> M_callcenter_clientes { get; set; }
        public virtual DbSet<M_callcenter_clientes_adicionales> M_callcenter_clientes_adicionales { get; set; }
        public virtual DbSet<P_Usuarios> P_Usuarios { get; set; }
        public virtual DbSet<PruPedUno> PruPedUno { get; set; }
        public virtual DbSet<sqlmapoutput> sqlmapoutput { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserLevelPermissions> UserLevelPermissions { get; set; }
        public virtual DbSet<UserLevels> UserLevels { get; set; }
        public virtual DbSet<C_APPCLIENT_TIPO_NOTIFICACIONES> C_APPCLIENT_TIPO_NOTIFICACIONES { get; set; }
        public virtual DbSet<C_APPCLIENT_TIPOS_DIRECCIONES> C_APPCLIENT_TIPOS_DIRECCIONES { get; set; }
        public virtual DbSet<C_APPEMP_BANNPROMOS> C_APPEMP_BANNPROMOS { get; set; }
        public virtual DbSet<C_catalogo_consecutivos> C_catalogo_consecutivos { get; set; }
        public virtual DbSet<C_catalogo_sn> C_catalogo_sn { get; set; }
        public virtual DbSet<C_catalogo_tamanos> C_catalogo_tamanos { get; set; }
        public virtual DbSet<C_CFDI_Municipios> C_CFDI_Municipios { get; set; }
        public virtual DbSet<C_Compac_Departamentos> C_Compac_Departamentos { get; set; }
        public virtual DbSet<C_Compac_Departamentos_Sucursales> C_Compac_Departamentos_Sucursales { get; set; }
        public virtual DbSet<C_Compac_Empleados_a_Procesar> C_Compac_Empleados_a_Procesar { get; set; }
        public virtual DbSet<C_Compac_Puestos> C_Compac_Puestos { get; set; }
        public virtual DbSet<C_compras_tipo_leyenda> C_compras_tipo_leyenda { get; set; }
        public virtual DbSet<C_Delivery_Anios> C_Delivery_Anios { get; set; }
        public virtual DbSet<C_Delivery_empresas_logo> C_Delivery_empresas_logo { get; set; }
        public virtual DbSet<C_Delivery_Img_Ingredientes> C_Delivery_Img_Ingredientes { get; set; }
        public virtual DbSet<C_Delivery_Mensajes_Whatsapp> C_Delivery_Mensajes_Whatsapp { get; set; }
        public virtual DbSet<C_Delivery_Ordenes_Tokens> C_Delivery_Ordenes_Tokens { get; set; }
        public virtual DbSet<C_Delivery_OrdenesPedidos> C_Delivery_OrdenesPedidos { get; set; }
        public virtual DbSet<C_Delivery_OrdenesPedidosCancelados> C_Delivery_OrdenesPedidosCancelados { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Plataformas_Corte> C_Delivery_Pagos_Plataformas_Corte { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados> C_Delivery_Pagos_Programados { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Bancos> C_Delivery_Pagos_Programados_Bancos { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Cuentas_Pago> C_Delivery_Pagos_Programados_Cuentas_Pago { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Cuentas_Tipo> C_Delivery_Pagos_Programados_Cuentas_Tipo { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Detalle> C_Delivery_Pagos_Programados_Detalle { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Detalle_Aclaracion> C_Delivery_Pagos_Programados_Detalle_Aclaracion { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Dispersion> C_Delivery_Pagos_Programados_Dispersion { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Extraordinarios> C_Delivery_Pagos_Programados_Extraordinarios { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Motivos> C_Delivery_Pagos_Programados_Motivos { get; set; }
        public virtual DbSet<C_Delivery_Pagos_Programados_Tipos> C_Delivery_Pagos_Programados_Tipos { get; set; }
        public virtual DbSet<C_Delivery_Params> C_Delivery_Params { get; set; }
        public virtual DbSet<C_Delivery_Pool_Notificaciones> C_Delivery_Pool_Notificaciones { get; set; }
        public virtual DbSet<C_Delivery_Pool_Notificaciones_Alcance> C_Delivery_Pool_Notificaciones_Alcance { get; set; }
        public virtual DbSet<C_Delivery_Pool_Notificaciones_Config> C_Delivery_Pool_Notificaciones_Config { get; set; }
        public virtual DbSet<C_Delivery_Pool_Notificaciones_Frecuencia> C_Delivery_Pool_Notificaciones_Frecuencia { get; set; }
        public virtual DbSet<C_Delivery_Pool_Notificaciones_Tipo> C_Delivery_Pool_Notificaciones_Tipo { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Actualiza_Domicilio> C_Delivery_Repartidores_Actualiza_Domicilio { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Cuentas> C_Delivery_Repartidores_Cuentas { get; set; }
        public virtual DbSet<C_Delivery_Repartidores_Disponibles> C_Delivery_Repartidores_Disponibles { get; set; }
        public virtual DbSet<C_Delivery_Semanas> C_Delivery_Semanas { get; set; }
        public virtual DbSet<C_Delivery_Servicios> C_Delivery_Servicios { get; set; }
        public virtual DbSet<C_Delivery_Setup_Empresas_Suc_Ser_Plat> C_Delivery_Setup_Empresas_Suc_Ser_Plat { get; set; }
        public virtual DbSet<C_Delivery_TablaErrores> C_Delivery_TablaErrores { get; set; }
        public virtual DbSet<C_Delivery_TipoCancelacion> C_Delivery_TipoCancelacion { get; set; }
        public virtual DbSet<C_Delivery_Trafico_Tracking> C_Delivery_Trafico_Tracking { get; set; }
        public virtual DbSet<C_Delivery_Trafico_Tracking_Log> C_Delivery_Trafico_Tracking_Log { get; set; }
        public virtual DbSet<C_descuentos> C_descuentos { get; set; }
        public virtual DbSet<C_empresas_servicios_contratados> C_empresas_servicios_contratados { get; set; }
        public virtual DbSet<C_impresion_cocina> C_impresion_cocina { get; set; }
        public virtual DbSet<C_insumo_tipo_inventario> C_insumo_tipo_inventario { get; set; }
        public virtual DbSet<C_microsip_cambios_log> C_microsip_cambios_log { get; set; }
        public virtual DbSet<C_productos_marca> C_productos_marca { get; set; }
        public virtual DbSet<C_proveedores> C_proveedores { get; set; }
        public virtual DbSet<C_servicios_tipo_contrato> C_servicios_tipo_contrato { get; set; }
        public virtual DbSet<C_servicios_tipo_recoleccion> C_servicios_tipo_recoleccion { get; set; }
        public virtual DbSet<C_sucursales_pool_clasificaciones> C_sucursales_pool_clasificaciones { get; set; }
        public virtual DbSet<C_sucursales_pool_division_impresion> C_sucursales_pool_division_impresion { get; set; }
        public virtual DbSet<C_sucursales_pool_impresoras> C_sucursales_pool_impresoras { get; set; }
        public virtual DbSet<C_sucursales_zonas_entregas> C_sucursales_zonas_entregas { get; set; }
        public virtual DbSet<C_sval_actas> C_sval_actas { get; set; }
        public virtual DbSet<C_sval_arqueos> C_sval_arqueos { get; set; }
        public virtual DbSet<C_sval_cat_desglose_billetes> C_sval_cat_desglose_billetes { get; set; }
        public virtual DbSet<C_sval_cat_desglose_denominacion> C_sval_cat_desglose_denominacion { get; set; }
        public virtual DbSet<C_sval_cat_desglose_monedas> C_sval_cat_desglose_monedas { get; set; }
        public virtual DbSet<C_sval_cliente_servicios> C_sval_cliente_servicios { get; set; }
        public virtual DbSet<C_sval_clientes> C_sval_clientes { get; set; }
        public virtual DbSet<C_sval_deposito_monedas> C_sval_deposito_monedas { get; set; }
        public virtual DbSet<C_sval_destinos_entrega> C_sval_destinos_entrega { get; set; }
        public virtual DbSet<C_sval_documentos> C_sval_documentos { get; set; }
        public virtual DbSet<C_sval_empresa_servicios> C_sval_empresa_servicios { get; set; }
        public virtual DbSet<C_sval_facturar_a> C_sval_facturar_a { get; set; }
        public virtual DbSet<C_sval_nominas_billetes> C_sval_nominas_billetes { get; set; }
        public virtual DbSet<C_sval_nominas_monedas> C_sval_nominas_monedas { get; set; }
        public virtual DbSet<C_sval_orden_billetes> C_sval_orden_billetes { get; set; }
        public virtual DbSet<C_sval_orden_monedas> C_sval_orden_monedas { get; set; }
        public virtual DbSet<C_sval_recepcion> C_sval_recepcion { get; set; }
        public virtual DbSet<C_sval_recepcion_billetes> C_sval_recepcion_billetes { get; set; }
        public virtual DbSet<C_sval_recepcion_monedas> C_sval_recepcion_monedas { get; set; }
        public virtual DbSet<C_sval_terminales> C_sval_terminales { get; set; }
        public virtual DbSet<C_sval_tipo_moneda> C_sval_tipo_moneda { get; set; }
        public virtual DbSet<C_sval_tipo_servicios> C_sval_tipo_servicios { get; set; }
        public virtual DbSet<C_TA_Transacciones> C_TA_Transacciones { get; set; }
        public virtual DbSet<C_tabla_d_puebas> C_tabla_d_puebas { get; set; }
        public virtual DbSet<C_usuarios_perfil_incentivos> C_usuarios_perfil_incentivos { get; set; }
        public virtual DbSet<C_usuarios_perfil_incentivos_rangos> C_usuarios_perfil_incentivos_rangos { get; set; }
        public virtual DbSet<C_usuarios_perfil_incentivos_roles> C_usuarios_perfil_incentivos_roles { get; set; }
        public virtual DbSet<C_zonas_entrega> C_zonas_entrega { get; set; }
        public virtual DbSet<P_encuesta_1> P_encuesta_1 { get; set; }
        public virtual DbSet<P_opciones> P_opciones { get; set; }
        public virtual DbSet<C_Delivery_Negocios_Clientes> C_Delivery_Negocios_Clientes { get; set; }
        public virtual DbSet<C_Delivery_Negocios_Direcciones> C_Delivery_Negocios_Direcciones { get; set; }
        public virtual DbSet<C_Delivery_Negocios_Telefonos> C_Delivery_Negocios_Telefonos { get; set; }
        public virtual DbSet<C_Delivery_Negocios_Telefonos_Clientes_Direcciones> C_Delivery_Negocios_Telefonos_Clientes_Direcciones { get; set; }
        public virtual DbSet<C_Delivery_Negocios_Tracking_Status> C_Delivery_Negocios_Tracking_Status { get; set; }
        public virtual DbSet<C_Delivery_Ordenes_Negocios> C_Delivery_Ordenes_Negocios { get; set; }
        public virtual DbSet<C_Delivery_Usuarios_Sucursales> C_Delivery_Usuarios_Sucursales { get; set; }
    
        public virtual ObjectResult<Delivery_61_Get_Trafico_Tracking_Result> Delivery_61_Get_Trafico_Tracking(string tOKEN, string fecha_desde, string fecha_hasta, string modo, string rangoPlataformas, string status, string rangoSucursales, string rangoRepartidores)
        {
            var tOKENParameter = tOKEN != null ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(string));
    
            var fecha_desdeParameter = fecha_desde != null ?
                new ObjectParameter("fecha_desde", fecha_desde) :
                new ObjectParameter("fecha_desde", typeof(string));
    
            var fecha_hastaParameter = fecha_hasta != null ?
                new ObjectParameter("fecha_hasta", fecha_hasta) :
                new ObjectParameter("fecha_hasta", typeof(string));
    
            var modoParameter = modo != null ?
                new ObjectParameter("Modo", modo) :
                new ObjectParameter("Modo", typeof(string));
    
            var rangoPlataformasParameter = rangoPlataformas != null ?
                new ObjectParameter("RangoPlataformas", rangoPlataformas) :
                new ObjectParameter("RangoPlataformas", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var rangoSucursalesParameter = rangoSucursales != null ?
                new ObjectParameter("RangoSucursales", rangoSucursales) :
                new ObjectParameter("RangoSucursales", typeof(string));
    
            var rangoRepartidoresParameter = rangoRepartidores != null ?
                new ObjectParameter("RangoRepartidores", rangoRepartidores) :
                new ObjectParameter("RangoRepartidores", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Delivery_61_Get_Trafico_Tracking_Result>("Delivery_61_Get_Trafico_Tracking", tOKENParameter, fecha_desdeParameter, fecha_hastaParameter, modoParameter, rangoPlataformasParameter, statusParameter, rangoSucursalesParameter, rangoRepartidoresParameter);
        }
    
        public virtual int Delivery_61_Get_Trafico_Tracking_Dashboard(string tOKEN, string fecha_desde, string fecha_hasta, string modo, string rangoPlataformas)
        {
            var tOKENParameter = tOKEN != null ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(string));
    
            var fecha_desdeParameter = fecha_desde != null ?
                new ObjectParameter("fecha_desde", fecha_desde) :
                new ObjectParameter("fecha_desde", typeof(string));
    
            var fecha_hastaParameter = fecha_hasta != null ?
                new ObjectParameter("fecha_hasta", fecha_hasta) :
                new ObjectParameter("fecha_hasta", typeof(string));
    
            var modoParameter = modo != null ?
                new ObjectParameter("Modo", modo) :
                new ObjectParameter("Modo", typeof(string));
    
            var rangoPlataformasParameter = rangoPlataformas != null ?
                new ObjectParameter("RangoPlataformas", rangoPlataformas) :
                new ObjectParameter("RangoPlataformas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delivery_61_Get_Trafico_Tracking_Dashboard", tOKENParameter, fecha_desdeParameter, fecha_hastaParameter, modoParameter, rangoPlataformasParameter);
        }
    
        public virtual ObjectResult<Delivery_61_Get_Trafico_Tracking_Rev1_Result> Delivery_61_Get_Trafico_Tracking_Rev1(string tOKEN, string fecha_desde, string fecha_hasta, string modo)
        {
            var tOKENParameter = tOKEN != null ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(string));
    
            var fecha_desdeParameter = fecha_desde != null ?
                new ObjectParameter("fecha_desde", fecha_desde) :
                new ObjectParameter("fecha_desde", typeof(string));
    
            var fecha_hastaParameter = fecha_hasta != null ?
                new ObjectParameter("fecha_hasta", fecha_hasta) :
                new ObjectParameter("fecha_hasta", typeof(string));
    
            var modoParameter = modo != null ?
                new ObjectParameter("Modo", modo) :
                new ObjectParameter("Modo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Delivery_61_Get_Trafico_Tracking_Rev1_Result>("Delivery_61_Get_Trafico_Tracking_Rev1", tOKENParameter, fecha_desdeParameter, fecha_hastaParameter, modoParameter);
        }
    
        public virtual int Delivery_61_Set_Trafico_Tracking(string tOKEN, Nullable<int> id_orden, string id_semaforo_trafico)
        {
            var tOKENParameter = tOKEN != null ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(string));
    
            var id_ordenParameter = id_orden.HasValue ?
                new ObjectParameter("id_orden", id_orden) :
                new ObjectParameter("id_orden", typeof(int));
    
            var id_semaforo_traficoParameter = id_semaforo_trafico != null ?
                new ObjectParameter("id_semaforo_trafico", id_semaforo_trafico) :
                new ObjectParameter("id_semaforo_trafico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delivery_61_Set_Trafico_Tracking", tOKENParameter, id_ordenParameter, id_semaforo_traficoParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> usp_Distancia_dos_puntos(Nullable<double> lat1, Nullable<double> long1, Nullable<double> lat2, Nullable<double> long2)
        {
            var lat1Parameter = lat1.HasValue ?
                new ObjectParameter("lat1", lat1) :
                new ObjectParameter("lat1", typeof(double));
    
            var long1Parameter = long1.HasValue ?
                new ObjectParameter("long1", long1) :
                new ObjectParameter("long1", typeof(double));
    
            var lat2Parameter = lat2.HasValue ?
                new ObjectParameter("lat2", lat2) :
                new ObjectParameter("lat2", typeof(double));
    
            var long2Parameter = long2.HasValue ?
                new ObjectParameter("long2", long2) :
                new ObjectParameter("long2", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("usp_Distancia_dos_puntos", lat1Parameter, long1Parameter, lat2Parameter, long2Parameter);
        }
    }
}
