//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPIDI_PORTAL.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruPedUno
    {
        public int id_back { get; set; }
        public string fecha { get; set; }
        public string sku_insumo { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<decimal> entradas { get; set; }
        public Nullable<decimal> salidas { get; set; }
        public Nullable<decimal> mermas { get; set; }
        public Nullable<decimal> ventas { get; set; }
        public decimal existencia_sug { get; set; }
    }
}
